/**
 * Seed script: March 2026 tax events for Uzbekistan
 * Source: TREK_UZ_CALENDAR_SPEC.md Part 3 (verified against НК РУз)
 *
 * Run: npx tsx prisma/seed-march-2026.ts
 */

import { PrismaClient, TaxType, EventType, OrgType, TaxRegime } from "@prisma/client";

const prisma = new PrismaClient();

const LLC_JSC = [OrgType.LLC, OrgType.JSC];
const LLC_JSC_IE = [OrgType.LLC, OrgType.JSC, OrgType.IE];
const LLC_JSC_IE_SE = [OrgType.LLC, OrgType.JSC, OrgType.IE, OrgType.SELF_EMPLOYED];
const IE_ONLY = [OrgType.IE];
const VAT_TURNOVER = [TaxRegime.VAT, TaxRegime.TURNOVER];
const VAT_ONLY = [TaxRegime.VAT];
const TURNOVER_ONLY = [TaxRegime.TURNOVER];

const events = [
  // ─────────── 2 марта (перенос с 1 марта — воскресенье) ───────────

  // #1 Годовая финансовая отчётность НСБУ за 2025
  {
    year: 2026, month: 3,
    date: new Date("2026-03-02"),
    originalDate: new Date("2026-03-01"),
    isPostponed: true,
    postponeReasonRu: "1 марта — воскресенье, срок переносится на следующий рабочий день",
    postponeReasonEn: "March 1 is Sunday, deadline moved to next working day",
    postponeReasonUz: "1 mart — yakshanba, muddat keyingi ish kuniga ko'chiriladi",
    postponeReasonUzc: "1 март — якшанба, муддат кейинги иш кунига кўчирилади",
    taxType: TaxType.OTHER,
    eventType: EventType.REPORT,
    titleRu: "Годовая финансовая отчётность по НСБУ за 2025 год",
    titleEn: "Annual financial statements under NSBU for 2025",
    titleUz: "2025 yil uchun NSBX bo'yicha yillik moliyaviy hisobot",
    titleUzc: "2025 йил учун НСБУ бўйича йиллик молиявий ҳисобот",
    descRu: "Юридические лица, ведущие учёт по НСБУ, представляют годовую финансовую отчётность за 2025 год. Срок перенесён с 1 марта (воскресенье) на 2 марта 2026 года.",
    descEn: "Legal entities under NSBU submit annual financial statements for 2025. Deadline moved from March 1 (Sunday) to March 2, 2026.",
    descUz: "NSBX bo'yicha hisob yurituvchi yuridik shaxslar 2025 yil uchun yillik moliyaviy hisobotni taqdim etadilar.",
    descUzc: "НСБУ бўйича ҳисоб юритувчи юридик шахслар 2025 йил учун йиллик молиявий ҳисоботни тақдим этадилар.",
    articleRef: "Приказ рег. МЮ №3567 п.7",
    orgTypes: LLC_JSC,
    taxRegimes: VAT_TURNOVER,
    isPublished: true, isDraft: false,
  },

  // #2 Сведения о контролируемых сделках за 2025
  {
    year: 2026, month: 3,
    date: new Date("2026-03-02"),
    originalDate: new Date("2026-03-01"),
    isPostponed: true,
    postponeReasonRu: "1 марта — воскресенье, срок переносится на следующий рабочий день",
    postponeReasonEn: "March 1 is Sunday, deadline moved to next working day",
    postponeReasonUz: "1 mart — yakshanba, muddat keyingi ish kuniga ko'chiriladi",
    postponeReasonUzc: "1 март — якшанба, муддат кейинги иш кунига кўчирилади",
    taxType: TaxType.PROFIT,
    eventType: EventType.REPORT,
    titleRu: "Сведения о контролируемых сделках за 2025 год",
    titleEn: "Information on controlled transactions for 2025",
    titleUz: "2025 yil uchun nazorat qilinadigan bitimlar to'g'risidagi ma'lumotlar",
    titleUzc: "2025 йил учун назорат қилинадиган битимлар тўғрисидаги маълумотлар",
    descRu: "Юридические лица представляют сведения о контролируемых сделках за 2025 год (трансфертное ценообразование). Срок перенесён с 1 марта на 2 марта 2026 года.",
    descEn: "Legal entities submit information on controlled transactions for 2025 (transfer pricing). Deadline moved to March 2, 2026.",
    descUz: "Yuridik shaxslar 2025 yil uchun nazorat qilinadigan bitimlar (transfer narxlash) to'g'risidagi ma'lumotlarni taqdim etadilar.",
    descUzc: "Юридик шахслар 2025 йил учун назорат қилинадиган битимлар (трансфер нарх белгилаш) тўғрисидаги маълумотларни тақдим этадилар.",
    articleRef: "ст.182 ч.2 НК",
    orgTypes: LLC_JSC,
    taxRegimes: VAT_TURNOVER,
    requiresSpecial: ["controlled_transactions"],
    isPublished: true, isDraft: false,
  },

  // #3 Налог на прибыль за 2025 (годовой) — отчётность и уплата
  {
    year: 2026, month: 3,
    date: new Date("2026-03-02"),
    originalDate: new Date("2026-03-01"),
    isPostponed: true,
    postponeReasonRu: "1 марта — воскресенье, срок переносится на следующий рабочий день",
    postponeReasonEn: "March 1 is Sunday, deadline moved to next working day",
    postponeReasonUz: "1 mart — yakshanba, muddat keyingi ish kuniga ko'chiriladi",
    postponeReasonUzc: "1 март — якшанба, муддат кейинги иш кунига кўчирилади",
    taxType: TaxType.PROFIT,
    eventType: EventType.BOTH,
    titleRu: "Отчётность и уплата налога на прибыль за 2025 год (годовой)",
    titleEn: "Annual corporate income tax reporting and payment for 2025",
    titleUz: "2025 yil uchun foyda solig'i bo'yicha yillik hisobot va to'lov",
    titleUzc: "2025 йил учун фойда солиғи бўйича йиллик ҳисобот ва тўлов",
    descRu: "Юридические лица представляют годовой расчёт и уплачивают налог на прибыль за 2025 год. Плательщики НсО также подают годовой расчёт (ст.462 ч.2 НК). Срок перенесён с 1 марта на 2 марта 2026 года.",
    descEn: "Legal entities file the annual corporate income tax return and pay for 2025. Turnover tax payers also file the annual return (Art.462 para.2 of Tax Code). Deadline moved to March 2, 2026.",
    descUz: "Yuridik shaxslar 2025 yil uchun yillik hisob-kitob taqdim etadilar va foyda solig'ini to'laydilar.",
    descUzc: "Юридик шахслар 2025 йил учун йиллик ҳисоб-китоб тақдим этадилар ва фойда солиғини тўлайдилар.",
    articleRef: "ст.339 ч.5 п.2, ст.340, ст.480 НК",
    orgTypes: LLC_JSC,
    taxRegimes: VAT_TURNOVER,
    isPublished: true, isDraft: false,
  },

  // #4 Налог на имущество за 2025 (годовой) — отчётность и уплата
  {
    year: 2026, month: 3,
    date: new Date("2026-03-02"),
    originalDate: new Date("2026-03-01"),
    isPostponed: true,
    postponeReasonRu: "1 марта — воскресенье, срок переносится на следующий рабочий день",
    postponeReasonEn: "March 1 is Sunday, deadline moved to next working day",
    postponeReasonUz: "1 mart — yakshanba, muddat keyingi ish kuniga ko'chiriladi",
    postponeReasonUzc: "1 март — якшанба, муддат кейинги иш кунига кўчирилади",
    taxType: TaxType.PROPERTY,
    eventType: EventType.BOTH,
    titleRu: "Отчётность и уплата налога на имущество за 2025 год (годовой)",
    titleEn: "Annual property tax reporting and payment for 2025",
    titleUz: "2025 yil uchun mulk solig'i bo'yicha yillik hisobot va to'lov",
    titleUzc: "2025 йил учун мулк солиғи бўйича йиллик ҳисобот ва тўлов",
    descRu: "Налогоплательщики представляют годовой расчёт налога на имущество за 2025 год и производят окончательную уплату.",
    descEn: "Taxpayers file the annual property tax return for 2025 and make the final payment.",
    descUz: "Soliq to'lovchilar 2025 yil uchun mulk solig'i bo'yicha yillik hisob-kitob taqdim etadilar va yakuniy to'lovni amalga oshiradilar.",
    descUzc: "Солиқ тўловчилар 2025 йил учун мулк солиғи бўйича йиллик ҳисоб-китоб тақдим этадилар ва якуний тўловни амалга оширадилар.",
    articleRef: "ст.417 чч.2,8 НК",
    orgTypes: LLC_JSC_IE,
    taxRegimes: VAT_TURNOVER,
    requiresAssets: ["property"],
    isPublished: true, isDraft: false,
  },

  // #5 Водный налог за 2025 (юрлица кроме сельхоз) — отчётность и уплата
  {
    year: 2026, month: 3,
    date: new Date("2026-03-02"),
    originalDate: new Date("2026-03-01"),
    isPostponed: true,
    postponeReasonRu: "1 марта — воскресенье, срок переносится на следующий рабочий день",
    postponeReasonEn: "March 1 is Sunday, deadline moved to next working day",
    postponeReasonUz: "1 mart — yakshanba, muddat keyingi ish kuniga ko'chiriladi",
    postponeReasonUzc: "1 март — якшанба, муддат кейинги иш кунига кўчирилади",
    taxType: TaxType.WATER,
    eventType: EventType.BOTH,
    titleRu: "Водный налог за 2025 год (юрлица, кроме сельхоз) — отчётность и уплата",
    titleEn: "Annual water use tax for 2025 (legal entities, non-agricultural)",
    titleUz: "2025 yil uchun suv solig'i (yuridik shaxslar, qishloq xo'jaligi emas)",
    titleUzc: "2025 йил учун сув солиғи (юридик шахслар, қишлоқ хўжалиги эмас)",
    descRu: "Юридические лица (не занимающиеся сельхозпроизводством) представляют годовую отчётность и уплачивают водный налог за 2025 год. Дехканские хозяйства платят до 1 мая по уведомлению.",
    descEn: "Legal entities (non-agricultural) file the annual water use tax return and pay for 2025. Farm households pay by May 1 per notification.",
    descUz: "Qishloq xo'jaligi bilan shug'ullanmaydigan yuridik shaxslar 2025 yil uchun suv solig'i bo'yicha yillik hisobot taqdim etadilar va to'laydilar.",
    descUzc: "Қишлоқ хўжалиги билан шуғулланмайдиган юридик шахслар 2025 йил учун сув солиғи бўйича йиллик ҳисобот тақдим этадилар ва тўлайдилар.",
    articleRef: "ст.447 ч.3, ст.448 ч.5 НК",
    orgTypes: LLC_JSC,
    taxRegimes: VAT_TURNOVER,
    requiresAssets: ["water"],
    isPublished: true, isDraft: false,
  },

  // #6 Спецрентный налог за 2025 (годовой)
  {
    year: 2026, month: 3,
    date: new Date("2026-03-02"),
    originalDate: new Date("2026-03-01"),
    isPostponed: true,
    postponeReasonRu: "1 марта — воскресенье, срок переносится на следующий рабочий день",
    postponeReasonEn: "March 1 is Sunday, deadline moved to next working day",
    postponeReasonUz: "1 mart — yakshanba, muddat keyingi ish kuniga ko'chiriladi",
    postponeReasonUzc: "1 март — якшанба, муддат кейинги иш кунига кўчирилади",
    taxType: TaxType.RENT,
    eventType: EventType.BOTH,
    titleRu: "Спецрентный налог за 2025 год (годовой)",
    titleEn: "Special rental tax for 2025 (annual)",
    titleUz: "2025 yil uchun maxsus renta solig'i (yillik)",
    titleUzc: "2025 йил учун махсус рента солиғи (йиллик)",
    descRu: "Юридические лица, осуществляющие добычу полезных ископаемых, представляют годовой расчёт и уплачивают специальный рентный налог за 2025 год.",
    descEn: "Legal entities engaged in mineral extraction file the annual return and pay special rental tax for 2025.",
    descUz: "Foydali qazilmalar qazib chiqaruvchi yuridik shaxslar 2025 yil uchun maxsus renta solig'i bo'yicha yillik hisob-kitob taqdim etadilar.",
    descUzc: "Фойдали қазилмалар қазиб чиқарувчи юридик шахслар 2025 йил учун махсус рента солиғи бўйича йиллик ҳисоб-китоб тақдим этадилар.",
    articleRef: "ст.454-7 НК",
    orgTypes: LLC_JSC,
    taxRegimes: VAT_ONLY,
    requiresSpecial: ["subsoil"],
    isPublished: true, isDraft: false,
  },

  // ─────────── 5 марта ───────────

  // #7 Налог на прибыль банков с нерезидентов за февраль 2026
  {
    year: 2026, month: 3,
    date: new Date("2026-03-05"),
    taxType: TaxType.PROFIT,
    eventType: EventType.PAYMENT,
    titleRu: "Уплата банками налога на прибыль с доходов нерезидентов за февраль 2026",
    titleEn: "Banks' profit tax on non-resident income for February 2026",
    titleUz: "Banklar tomonidan 2026 yil fevral uchun norezidentlar daromadidan foyda solig'i",
    titleUzc: "Банклар томонидан 2026 йил феврал учун норезидентлар даромадидан фойда солиғи",
    descRu: "Банки уплачивают налог на прибыль с доходов, выплаченных нерезидентам в феврале 2026 года (за исключением дивидендов и процентов). Показывается всем с признаком non_resident_income, т.к. банки — подтип юрлиц.",
    descEn: "Banks pay profit tax on income paid to non-residents in February 2026 (except dividends and interest).",
    descUz: "Banklar 2026 yil fevral oyida norezidentlarga to'langan daromadlardan foyda solig'ini to'laydilar.",
    descUzc: "Банклар 2026 йил феврал ойида норезидентларга тўланган даромадлардан фойда солиғини тўлайдилар.",
    articleRef: "ст.355 ч.2 п.1 НК",
    orgTypes: LLC_JSC,
    taxRegimes: VAT_TURNOVER,
    requiresSpecial: ["non_resident_income"],
    isPublished: true, isDraft: false,
  },

  // ─────────── 6 марта ───────────

  // #8 НДФЛ и ИНПС с натуральных выплат за февраль 2026
  {
    year: 2026, month: 3,
    date: new Date("2026-03-06"),
    taxType: TaxType.PERSONAL_IT,
    eventType: EventType.PAYMENT,
    titleRu: "НДФЛ и ИНПС с доходов в натуральной форме за февраль 2026",
    titleEn: "PIT and INPS on in-kind income for February 2026",
    titleUz: "2026 yil fevral uchun natural shaklda to'langan daromadlardan JSST va INPS",
    titleUzc: "2026 йил феврал учун натурал шаклда тўланган даромадлардан ЖССТ ва ИНПС",
    descRu: "При выплате доходов в натуральной форме НДФЛ и взносы ИНПС уплачиваются в течение 5 рабочих дней после окончания месяца выплаты.",
    descEn: "When income is paid in kind, PIT and INPS contributions are paid within 5 working days after the end of the payment month.",
    descUz: "Natural shaklda to'langan daromadlar uchun JSST va INPS to'lovlar oyning oxiridan 5 ish kuni ichida amalga oshiriladi.",
    descUzc: "Натурал шаклда тўланган даромадлар учун ЖССТ ва ИНПС тўловлар ойнинг охиридан 5 иш куни ичида амалга оширилади.",
    articleRef: "ст.390 ч.2, Положение МЮ №3577 п.6",
    orgTypes: LLC_JSC_IE,
    taxRegimes: VAT_TURNOVER,
    requiresEmployees: true,
    isPublished: true, isDraft: false,
  },

  // ─────────── 10 марта (перенос с 9 марта — выходной) ───────────

  // #9 Сборы за реализацию алкоголя/пива/табака за март 2026
  {
    year: 2026, month: 3,
    date: new Date("2026-03-10"),
    originalDate: new Date("2026-03-09"),
    isPostponed: true,
    postponeReasonRu: "9 марта — выходной, срок переносится на следующий рабочий день",
    postponeReasonEn: "March 9 is a holiday, deadline moved to next working day",
    postponeReasonUz: "9 mart — dam olish kuni, muddat keyingi ish kuniga ko'chiriladi",
    postponeReasonUzc: "9 март — дам олиш куни, муддат кейинги иш кунига кўчирилади",
    taxType: TaxType.FEES,
    eventType: EventType.PAYMENT,
    titleRu: "Сборы за право реализации алкоголя, пива, табака за март 2026",
    titleEn: "Fees for right to sell alcohol, beer, tobacco for March 2026",
    titleUz: "Mart 2026 uchun spirtli ichimliklar, pivo, tamaki sotish huquqi uchun yig'imlar",
    titleUzc: "Март 2026 учун спиртли ичимликлар, пиво, тамаки сотиш ҳуқуқи учун йиғимлар",
    descRu: "Предоплата сборов за право реализации алкоголя, пива и табака за март 2026 года. Срок перенесён с 9 марта на 10 марта.",
    descEn: "Advance payment of fees for right to sell alcohol, beer and tobacco for March 2026. Deadline moved from March 9 to March 10.",
    descUz: "Mart 2026 uchun spirtli ichimliklar, pivo va tamaki sotish huquqi uchun yig'imlarni oldindan to'lash.",
    descUzc: "Март 2026 учун спиртли ичимликлар, пиво ва тамаки сотиш ҳуқуқи учун йиғимларни олдиндан тўлаш.",
    articleRef: "ст.460 ч.6 НК",
    orgTypes: LLC_JSC,
    taxRegimes: VAT_TURNOVER,
    requiresSpecial: ["alcohol_tobacco"],
    isPublished: true, isDraft: false,
  },

  // #10 Акцизный налог за февраль 2026 — отчётность и уплата
  {
    year: 2026, month: 3,
    date: new Date("2026-03-10"),
    taxType: TaxType.EXCISE,
    eventType: EventType.BOTH,
    titleRu: "Отчётность и уплата акцизного налога за февраль 2026",
    titleEn: "Excise tax reporting and payment for February 2026",
    titleUz: "2026 yil fevral uchun aksiz solig'i hisoboti va to'lovi",
    titleUzc: "2026 йил феврал учун акциз солиғи ҳисоботи ва тўлови",
    descRu: "Плательщики акцизного налога представляют отчётность и уплачивают налог за февраль 2026 года. Плательщики НсО освобождены (ст.461 НК).",
    descEn: "Excise tax payers file the return and pay for February 2026. Turnover tax payers are excluded (Art.461 of Tax Code).",
    descUz: "Aksiz solig'i to'lovchilari 2026 yil fevral uchun hisobot topshiradilar va soliq to'laydilar. NsO to'lovchilar bundan mustasno (st.461 NK).",
    descUzc: "Акциз солиғи тўловчилари 2026 йил феврал учун ҳисобот топшириш ва солиқ тўлайдилар. НсО тўловчилар бундан мустасно (ст.461 НК).",
    articleRef: "ст.292, 293 НК",
    orgTypes: LLC_JSC,
    taxRegimes: VAT_ONLY,
    requiresSpecial: ["excise"],
    isPublished: true, isDraft: false,
  },

  // #11 Авансы по налогу на имущество за март 2026 (1/12)
  {
    year: 2026, month: 3,
    date: new Date("2026-03-10"),
    taxType: TaxType.PROPERTY,
    eventType: EventType.PAYMENT,
    titleRu: "Авансовый платёж по налогу на имущество за март 2026 (1/12)",
    titleEn: "Property tax advance payment for March 2026 (1/12)",
    titleUz: "Mart 2026 uchun mulk solig'i bo'yicha avans to'lov (1/12)",
    titleUzc: "Март 2026 учун мулк солиғи бўйича аванс тўлов (1/12)",
    descRu: "Плательщики НДС уплачивают ежемесячный авансовый платёж по налогу на имущество за март 2026 года в размере 1/12 годовой суммы. Плательщики НсО платят квартально 20-го числа.",
    descEn: "VAT payers remit the monthly property tax advance for March 2026 (1/12 of annual amount). Turnover tax payers pay quarterly by the 20th.",
    descUz: "QQS to'lovchilari mart 2026 uchun mulk solig'i bo'yicha oylik avans to'lovini amalga oshiradilar (yillik summasining 1/12).",
    descUzc: "ҚҚС тўловчилари март 2026 учун мулк солиғи бўйича ойлик аванс тўловини амалга оширадилар (йиллик суммасининг 1/12).",
    articleRef: "ст.417 ч.6 НК",
    orgTypes: LLC_JSC_IE,
    taxRegimes: VAT_ONLY,
    requiresAssets: ["property"],
    isPublished: true, isDraft: false,
  },

  // #12 Земельный налог несельхоз за март 2026 (1/12)
  {
    year: 2026, month: 3,
    date: new Date("2026-03-10"),
    taxType: TaxType.LAND,
    eventType: EventType.PAYMENT,
    titleRu: "Земельный налог (несельхоз) за март 2026 (1/12)",
    titleEn: "Land tax (non-agricultural) for March 2026 (1/12)",
    titleUz: "Mart 2026 uchun yer solig'i (qishloq xo'jaligi bo'lmagan) (1/12)",
    titleUzc: "Март 2026 учун ер солиғи (қишлоқ хўжалиги бўлмаган) (1/12)",
    descRu: "Плательщики НДС уплачивают ежемесячный платёж по земельному налогу за несельхозугодья за март 2026 года (1/12 годовой суммы). Плательщики НсО платят квартально.",
    descEn: "VAT payers remit the monthly land tax for non-agricultural land for March 2026 (1/12 of annual amount). Turnover tax payers pay quarterly.",
    descUz: "QQS to'lovchilari mart 2026 uchun qishloq xo'jaligi maqsadlarida foydalanilmaydigan yerlar uchun yer solig'ini to'laydilar (1/12).",
    descUzc: "ҚҚС тўловчилари март 2026 учун қишлоқ хўжалиги мақсадларида фойдаланилмайдиган ерлар учун ер солиғини тўлайдилар (1/12).",
    articleRef: "ст.432 ч.1 НК",
    orgTypes: LLC_JSC_IE,
    taxRegimes: VAT_ONLY,
    requiresAssets: ["land_non_agri"],
    isPublished: true, isDraft: false,
  },

  // #13 Заявка в ПФ (ребёнок-инвалид) за февраль 2026
  {
    year: 2026, month: 3,
    date: new Date("2026-03-10"),
    taxType: TaxType.OTHER,
    eventType: EventType.REPORT,
    titleRu: "Заявка в Пенсионный фонд (ребёнок-инвалид) за февраль 2026",
    titleEn: "Pension Fund application (disabled child) for February 2026",
    titleUz: "Fevral 2026 uchun Pensiya jamg'armasiga ariza (nogironligi bo'lgan bola)",
    titleUzc: "Феврал 2026 учун Пенсия жамғармасига ариза (ногиронлиги бўлган бола)",
    descRu: "Работодатели подают ежемесячную заявку в Пенсионный фонд на возмещение расходов по выплате пенсий детям-инвалидам до 16 лет за февраль 2026 года.",
    descEn: "Employers submit monthly application to the Pension Fund for reimbursement of disability pensions for children under 16 for February 2026.",
    descUz: "Ish beruvchilar 16 yoshgacha bo'lgan nogironligi bo'lgan bolalar pensiyasi xarajatlarini qoplash uchun Pensiya jamg'armasiga oylik ariza topshiradilar.",
    descUzc: "Иш берувчилар 16 ёшгача бўлган ногиронлиги бўлган болалар пенсияси харажатларини қоплаш учун Пенсия жамғармасига ойлик ариза топшириш.",
    articleRef: "ПКМ №661 пп.45-46",
    orgTypes: LLC_JSC_IE,
    taxRegimes: VAT_TURNOVER,
    requiresEmployees: true,
    requiresPension: ["disabled_child"],
    isPublished: true, isDraft: false,
  },

  // ─────────── 16 марта (перенос с 15 марта — воскресенье) ───────────

  // #14 Реестры и уплата ИНПС за февраль 2026
  {
    year: 2026, month: 3,
    date: new Date("2026-03-16"),
    originalDate: new Date("2026-03-15"),
    isPostponed: true,
    postponeReasonRu: "15 марта — воскресенье, срок переносится на следующий рабочий день",
    postponeReasonEn: "March 15 is Sunday, deadline moved to next working day",
    postponeReasonUz: "15 mart — yakshanba, muddat keyingi ish kuniga ko'chiriladi",
    postponeReasonUzc: "15 март — якшанба, муддат кейинги иш кунига кўчирилади",
    taxType: TaxType.INPS,
    eventType: EventType.BOTH,
    titleRu: "Реестры и уплата ИНПС за февраль 2026",
    titleEn: "INPS registers and contributions for February 2026",
    titleUz: "Fevral 2026 uchun INPS reestrlari va badallari",
    titleUzc: "Феврал 2026 учун ИНПС рееструлари ва бадаллари",
    descRu: "Работодатели представляют реестры и уплачивают взносы на индивидуальные накопительные пенсионные счета (ИНПС) за февраль 2026 года. Срок перенесён с 15 марта (воскресенье) на 16 марта.",
    descEn: "Employers submit registers and pay INPS contributions for February 2026. Deadline moved from March 15 (Sunday) to March 16.",
    descUz: "Ish beruvchilar fevral 2026 uchun INPS rejestrlarini topshiradilar va badallarni to'laydilar.",
    descUzc: "Иш берувчилар феврал 2026 учун ИНПС рееструларини топшириш ва бадалларни тўлайдилар.",
    articleRef: "Положение МЮ №3577 пп.6,9",
    orgTypes: LLC_JSC_IE,
    taxRegimes: VAT_TURNOVER,
    requiresEmployees: true,
    isPublished: true, isDraft: false,
  },

  // #15 НДФЛ и соцналог за февраль 2026
  {
    year: 2026, month: 3,
    date: new Date("2026-03-16"),
    originalDate: new Date("2026-03-15"),
    isPostponed: true,
    postponeReasonRu: "15 марта — воскресенье, срок переносится на следующий рабочий день",
    postponeReasonEn: "March 15 is Sunday, deadline moved to next working day",
    postponeReasonUz: "15 mart — yakshanba, muddat keyingi ish kuniga ko'chiriladi",
    postponeReasonUzc: "15 март — якшанба, муддат кейинги иш кунига кўчирилади",
    taxType: TaxType.SOCIAL,
    eventType: EventType.BOTH,
    titleRu: "Отчётность и уплата НДФЛ и социального налога за февраль 2026",
    titleEn: "PIT and social tax reporting and payment for February 2026",
    titleUz: "Fevral 2026 uchun JSST va ijtimoiy soliq hisoboti va to'lovi",
    titleUzc: "Феврал 2026 учун ЖССТ ва ижтимоий солиқ ҳисоботи ва тўлови",
    descRu: "Работодатели представляют отчётность и уплачивают НДФЛ и социальный налог за февраль 2026 года. Срок перенесён с 15 марта (воскресенье) на 16 марта.",
    descEn: "Employers file the return and pay PIT and social tax for February 2026. Deadline moved from March 15 (Sunday) to March 16.",
    descUz: "Ish beruvchilar fevral 2026 uchun JSST va ijtimoiy soliq bo'yicha hisobot topshiradilar va to'laydilar.",
    descUzc: "Иш берувчилар феврал 2026 учун ЖССТ ва ижтимоий солиқ бўйича ҳисобот топшириш ва тўлайдилар.",
    articleRef: "ст.389, 390, 407 НК",
    orgTypes: LLC_JSC_IE,
    taxRegimes: VAT_TURNOVER,
    requiresEmployees: true,
    isPublished: true, isDraft: false,
  },

  // #15b Соцналог ИП за себя — февраль 2026 (обязательный, ст.408 п.1)
  {
    year: 2026, month: 3,
    date: new Date("2026-03-16"),
    originalDate: new Date("2026-03-15"),
    isPostponed: true,
    postponeReasonRu: "15 марта — воскресенье, срок переносится на следующий рабочий день",
    postponeReasonEn: "March 15 is Sunday, deadline moved to next working day",
    postponeReasonUz: "15 mart — yakshanba, muddat keyingi ish kuniga ko'chiriladi",
    postponeReasonUzc: "15 март — якшанба, муддат кейинги иш кунига кўчирилади",
    taxType: TaxType.SOCIAL,
    eventType: EventType.PAYMENT,
    titleRu: "Уплата соцналога ИП за себя за февраль 2026 (≥1 БРВ/мес)",
    titleEn: "IE mandatory personal social tax for February 2026 (≥1 BRV/month)",
    titleUz: "YaTT uchun shaxsiy ijtimoiy soliq to'lovi — fevral 2026 (≥1 BHM/oy)",
    titleUzc: "ЯТТ учун шахсий ижтимоий солиқ тўлови — феврал 2026 (≥1 БҲМ/ой)",
    descRu: "Индивидуальные предприниматели уплачивают обязательный социальный налог за себя — не менее 1 БРВ в месяц (ст.408 п.1 НК). Обязательство действует независимо от наличия наёмных работников. Срок перенесён с 15 марта на 16 марта.",
    descEn: "Individual entrepreneurs pay mandatory personal social tax of at least 1 BRV per month (Art. 408 para. 1 of the Tax Code). This obligation applies regardless of whether they have employees. Deadline moved to March 16.",
    descUz: "Yakka tartibdagi tadbirkorlar (YaTT) o'zlari uchun oyiga kamida 1 BHM miqdorida ijtimoiy soliq to'lashlari shart (NK 408-modda 1-band). Bu majburiyat xodimlari bormi yo yo'qmi — farq qilmaydi.",
    descUzc: "Якка тартибдаги тадбиркорлар (ЯТТ) ўзлари учун ойига камида 1 БҲМ миқдорида ижтимоий солиқ тўлашлари шарт (НК 408-модда 1-банд). Бу мажбурият ходимлари борми йўқми — фарқ қилмайди.",
    articleRef: "ст.408 п.1 НК",
    orgTypes: IE_ONLY,
    taxRegimes: VAT_TURNOVER,
    isPublished: true, isDraft: false,
  },

  // #16 Налог с оборота за февраль 2026
  {
    year: 2026, month: 3,
    date: new Date("2026-03-16"),
    originalDate: new Date("2026-03-15"),
    isPostponed: true,
    postponeReasonRu: "15 марта — воскресенье, срок переносится на следующий рабочий день",
    postponeReasonEn: "March 15 is Sunday, deadline moved to next working day",
    postponeReasonUz: "15 mart — yakshanba, muddat keyingi ish kuniga ko'chiriladi",
    postponeReasonUzc: "15 март — якшанба, муддат кейинги иш кунига кўчирилади",
    taxType: TaxType.TURNOVER,
    eventType: EventType.BOTH,
    titleRu: "Отчётность и уплата налога с оборота за февраль 2026",
    titleEn: "Turnover tax reporting and payment for February 2026",
    titleUz: "Fevral 2026 uchun aylanma soliq hisoboti va to'lovi",
    titleUzc: "Феврал 2026 учун айланма солиқ ҳисоботи ва тўлови",
    descRu: "Плательщики налога с оборота (НсО) представляют отчётность и уплачивают налог за февраль 2026 года. Самозанятые — только если получают доход напрямую от физлиц. Срок перенесён с 15 на 16 марта.",
    descEn: "Turnover tax payers file return and pay for February 2026. Self-employed — only if receiving income directly from individuals. Deadline moved to March 16.",
    descUz: "Aylanma soliq to'lovchilari fevral 2026 uchun hisobot topshiradilar va soliq to'laydilar. Mustaqil ishlovchilar — faqat jismoniy shaxslardan to'g'ridan-to'g'ri daromad olsa.",
    descUzc: "Айланма солиқ тўловчилари феврал 2026 учун ҳисобот топшириш ва солиқ тўлайдилар.",
    articleRef: "ст.470 НК",
    orgTypes: LLC_JSC_IE_SE,
    taxRegimes: TURNOVER_ONLY,
    isPublished: true, isDraft: false,
  },

  // #17 НсО по доходам ИП/самозанятых (налоговые агенты) за февраль 2026
  {
    year: 2026, month: 3,
    date: new Date("2026-03-16"),
    originalDate: new Date("2026-03-15"),
    isPostponed: true,
    postponeReasonRu: "15 марта — воскресенье, срок переносится на следующий рабочий день",
    postponeReasonEn: "March 15 is Sunday, deadline moved to next working day",
    postponeReasonUz: "15 mart — yakshanba, muddat keyingi ish kuniga ko'chiriladi",
    postponeReasonUzc: "15 март — якшанба, муддат кейинги иш кунига кўчирилади",
    taxType: TaxType.TURNOVER,
    eventType: EventType.BOTH,
    titleRu: "НсО налоговые агенты по доходам ИП/самозанятых за февраль 2026",
    titleEn: "Turnover tax agents for IE/self-employed income for February 2026",
    titleUz: "Fevral 2026 uchun YaTT/mustaqil ishlovchilar daromadidan NsO soliq agentlari",
    titleUzc: "Феврал 2026 учун ЯТТ/мустақил ишловчилар даромадидан НсО солиқ агентлари",
    descRu: "Юридические лица — налоговые агенты удерживают и перечисляют НсО с доходов, выплаченных ИП и самозанятым в феврале 2026 года (ст.465 чч.4-5 НК).",
    descEn: "Legal entities acting as tax agents withhold and remit turnover tax on income paid to IE and self-employed in February 2026.",
    descUz: "Yuridik shaxslar — soliq agentlari fevral 2026 da YaTT va mustaqil ishlovchilarga to'langan daromadlardan NsO ni ushlab qolishadi va o'tkazishadi.",
    descUzc: "Юридик шахслар — солиқ агентлари феврал 2026 да ЯТТ ва мустақил ишловчиларга тўланган даромадлардан НсО ни ушлаб қолишади.",
    articleRef: "ст.470, ст.465 чч.4-5 НК",
    orgTypes: LLC_JSC,
    taxRegimes: TURNOVER_ONLY,
    isPublished: true, isDraft: false,
  },

  // #18 Исправление ошибок ККТ за февраль 2026 (плательщики НсО)
  {
    year: 2026, month: 3,
    date: new Date("2026-03-16"),
    originalDate: new Date("2026-03-15"),
    isPostponed: true,
    postponeReasonRu: "15 марта — воскресенье, срок переносится на следующий рабочий день",
    postponeReasonEn: "March 15 is Sunday, deadline moved to next working day",
    postponeReasonUz: "15 mart — yakshanba, muddat keyingi ish kuniga ko'chiriladi",
    postponeReasonUzc: "15 март — якшанба, муддат кейинги иш кунига кўчирилади",
    taxType: TaxType.TURNOVER,
    eventType: EventType.REPORT,
    titleRu: "Исправление ошибок ККТ за февраль 2026 (плательщики НсО)",
    titleEn: "Correction of online cash register errors for February 2026 (turnover tax payers)",
    titleUz: "Fevral 2026 uchun KKM xatolarini tuzatish (NsO to'lovchilari)",
    titleUzc: "Феврал 2026 учун ККМ хатоларини тузатиш (НсО тўловчилари)",
    descRu: "Последний день исправления технических ошибок в чеках онлайн-ККТ за февраль 2026 года для плательщиков налога с оборота (влияет на налоговую базу НсО).",
    descEn: "Last day to correct technical errors in online cash register receipts for February 2026 for turnover tax payers.",
    descUz: "Aylanma soliq to'lovchilari uchun fevral 2026 davri bo'yicha onlayn-KKM cheklaridagi texnik xatolarni tuzatishning oxirgi kuni.",
    descUzc: "Айланма солиқ тўловчилари учун феврал 2026 даври бўйича онлайн-ККМ чекларидаги техник хатоларни тузатишнинг охирги куни.",
    articleRef: "ПКМ №943 п.38-1, ст.470 НК",
    orgTypes: LLC_JSC_IE,
    taxRegimes: TURNOVER_ONLY,
    requiresSpecial: ["online_kkt"],
    isPublished: true, isDraft: false,
  },

  // ─────────── 24 марта (перенос с 20 марта — Руза хайит, 23 марта — выходной Навруз) ───────────

  // #19 Уведомление о КИК за 2025
  {
    year: 2026, month: 3,
    date: new Date("2026-03-24"),
    originalDate: new Date("2026-03-20"),
    isPostponed: true,
    postponeReasonRu: "20 марта — Руза хайит, 21–23 марта — Навруз; срок переносится на 24 марта",
    postponeReasonEn: "March 20 — Ruza Hayit, March 21–23 — Navruz holidays; deadline moved to March 24",
    postponeReasonUz: "20 mart — Ro'za hayit, 21–23 mart — Navro'z bayrami; muddat 24 martga ko'chirildi",
    postponeReasonUzc: "20 март — Рўза ҳайит, 21–23 март — Навруз байрами; муддат 24 мартга кўчирилди",
    taxType: TaxType.PROFIT,
    eventType: EventType.REPORT,
    titleRu: "Уведомление о КИК (контролируемые иностранные компании) за 2025 год",
    titleEn: "CFC (controlled foreign company) notification for 2025",
    titleUz: "2025 yil uchun KXK (nazorat qilinadigan xorijiy kompaniya) to'g'risida bildirishnoma",
    titleUzc: "2025 йил учун КХК (назорат қилинадиган хорижий компания) тўғрисида билдиришнома",
    descRu: "Налогоплательщики, признаваемые контролирующими лицами иностранных компаний (КИК), подают уведомление за 2025 год. Также применимо к физлицам (ИП, самозанятые), владеющим КИК.",
    descEn: "Taxpayers recognized as controlling persons of foreign companies (CFC) submit notification for 2025. Also applies to individuals (IE, self-employed) owning CFCs.",
    descUz: "Xorijiy kompaniyalarni nazorat qiluvchi shaxslar sifatida tan olingan soliq to'lovchilar 2025 yil uchun bildirishnoma topshiradilar.",
    descUzc: "Хорижий компанияларни назорат қилувчи шахслар сифатида тан олинган солиқ тўловчилар 2025 йил учун билдиришнома топшириш.",
    articleRef: "ст.209 ч.3 НК",
    orgTypes: LLC_JSC_IE_SE,
    taxRegimes: VAT_TURNOVER,
    requiresSpecial: ["cfc"],
    isPublished: true, isDraft: false,
  },

  // #20 НДС за февраль 2026 — отчётность и уплата
  {
    year: 2026, month: 3,
    date: new Date("2026-03-24"),
    originalDate: new Date("2026-03-20"),
    isPostponed: true,
    postponeReasonRu: "20 марта — Руза хайит, 21–23 марта — Навруз; срок переносится на 24 марта",
    postponeReasonEn: "March 20 — Ruza Hayit, March 21–23 — Navruz holidays; deadline moved to March 24",
    postponeReasonUz: "20 mart — Ro'za hayit, 21–23 mart — Navro'z; muddat 24 martga ko'chirildi",
    postponeReasonUzc: "20 март — Рўза ҳайит, 21–23 март — Навруз; муддат 24 мартга кўчирилди",
    taxType: TaxType.VAT,
    eventType: EventType.BOTH,
    titleRu: "Отчётность и уплата НДС за февраль 2026",
    titleEn: "VAT reporting and payment for February 2026",
    titleUz: "Fevral 2026 uchun QQS hisoboti va to'lovi",
    titleUzc: "Феврал 2026 учун ҚҚС ҳисоботи ва тўлови",
    descRu: "Плательщики НДС представляют отчётность и уплачивают налог за февраль 2026 года. Срок перенесён с 20 марта на 24 марта в связи с праздниками.",
    descEn: "VAT payers file the return and pay for February 2026. Deadline moved from March 20 to March 24 due to holidays.",
    descUz: "QQS to'lovchilari fevral 2026 uchun hisobot topshiradilar va soliq to'laydilar.",
    descUzc: "ҚҚС тўловчилари феврал 2026 учун ҳисобот топшириш ва солиқ тўлайдилар.",
    articleRef: "ст.273 НК",
    orgTypes: LLC_JSC_IE,
    taxRegimes: VAT_ONLY,
    isPublished: true, isDraft: false,
  },

  // #21 НДС налоговые агенты за февраль 2026
  {
    year: 2026, month: 3,
    date: new Date("2026-03-24"),
    originalDate: new Date("2026-03-20"),
    isPostponed: true,
    postponeReasonRu: "20 марта — Руза хайит, 21–23 марта — Навруз; срок переносится на 24 марта",
    postponeReasonEn: "March 20 — Ruza Hayit, March 21–23 — Navruz holidays; deadline moved to March 24",
    postponeReasonUz: "20 mart — Ro'za hayit, 21–23 mart — Navro'z; muddat 24 martga ko'chirildi",
    postponeReasonUzc: "20 март — Рўза ҳайит, 21–23 март — Навруз; муддат 24 мартга кўчирилди",
    taxType: TaxType.VAT,
    eventType: EventType.BOTH,
    titleRu: "НДС налоговые агенты за февраль 2026 (иностр. лица, госимущество)",
    titleEn: "VAT tax agents for February 2026 (foreign entities, state property)",
    titleUz: "Fevral 2026 uchun QQS soliq agentlari (xorijiy shaxslar, davlat mulki)",
    titleUzc: "Феврал 2026 учун ҚҚС солиқ агентлари (хорижий шахслар, давлат мулки)",
    descRu: "Налоговые агенты по НДС (при выплатах иностранным лицам и операциях с государственным имуществом) представляют отчётность и уплачивают налог за февраль 2026 года.",
    descEn: "VAT tax agents (for payments to foreign entities and state property transactions) file and pay for February 2026.",
    descUz: "QQS soliq agentlari (xorijiy shaxslarga to'lovlar va davlat mulki operatsiyalari) fevral 2026 uchun hisobot topshiradilar.",
    descUzc: "ҚҚС солиқ агентлари (хорижий шахсларга тўловлар ва давлат мулки операциялари) феврал 2026 учун ҳисобот топшириш.",
    articleRef: "ст.273, 255, 256 НК",
    orgTypes: LLC_JSC_IE,
    taxRegimes: VAT_ONLY,
    isPublished: true, isDraft: false,
  },

  // #22 Авансы по водному налогу
  {
    year: 2026, month: 3,
    date: new Date("2026-03-24"),
    originalDate: new Date("2026-03-20"),
    isPostponed: true,
    postponeReasonRu: "20 марта — Руза хайит, 21–23 марта — Навруз; срок переносится на 24 марта",
    postponeReasonEn: "March 20 — Ruza Hayit, March 21–23 — Navruz holidays; deadline moved to March 24",
    postponeReasonUz: "20 mart — Ro'za hayit, 21–23 mart — Navro'z; muddat 24 martga ko'chirildi",
    postponeReasonUzc: "20 март — Рўза ҳайит, 21–23 март — Навруз; муддат 24 мартга кўчирилди",
    taxType: TaxType.WATER,
    eventType: EventType.PAYMENT,
    titleRu: "Авансовый платёж по водному налогу (март 2026 или I кв 2026)",
    titleEn: "Water use tax advance (March 2026 or Q1 2026)",
    titleUz: "Suv solig'i avans to'lovi (mart 2026 yoki I chorak 2026)",
    titleUzc: "Сув солиғи аванс тўлови (март 2026 ёки I чорак 2026)",
    descRu: "Плательщики НДС с суммой >200 БРВ уплачивают 1/12 за март; остальные плательщики (НДС <200 БРВ, НсО, ИП) — 1/4 за I квартал.",
    descEn: "VAT payers with tax > 200 BRV pay 1/12 for March; others (VAT < 200 BRV, turnover tax, IE) pay 1/4 for Q1.",
    descUz: "Yillik summa 200 BHM dan ortiq QQS to'lovchilari mart uchun 1/12 to'laydilar; qolgan to'lovchilar I chorak uchun 1/4 to'laydilar.",
    descUzc: "Йиллик сумма 200 БҲМ дан ортиқ ҚҚС тўловчилари март учун 1/12 тўлайдилар; қолган тўловчилар I чорак учун 1/4 тўлайдилар.",
    articleRef: "ст.448 ч.3 НК",
    orgTypes: LLC_JSC_IE,
    taxRegimes: VAT_TURNOVER,
    requiresAssets: ["water"],
    isPublished: true, isDraft: false,
  },

  // #23 Земельный налог I кв 2026 (НсО, 1/4)
  {
    year: 2026, month: 3,
    date: new Date("2026-03-24"),
    originalDate: new Date("2026-03-20"),
    isPostponed: true,
    postponeReasonRu: "20 марта — Руза хайит, 21–23 марта — Навруз; срок переносится на 24 марта",
    postponeReasonEn: "March 20 — Ruza Hayit, March 21–23 — Navruz holidays; deadline moved to March 24",
    postponeReasonUz: "20 mart — Ro'za hayit, 21–23 mart — Navro'z; muddat 24 martga ko'chirildi",
    postponeReasonUzc: "20 март — Рўза ҳайит, 21–23 март — Навруз; муддат 24 мартга кўчирилди",
    taxType: TaxType.LAND,
    eventType: EventType.PAYMENT,
    titleRu: "Земельный налог I квартал 2026 (1/4, плательщики НсО)",
    titleEn: "Land tax Q1 2026 (1/4, turnover tax payers)",
    titleUz: "Yer solig'i I chorak 2026 (1/4, NsO to'lovchilari)",
    titleUzc: "Ер солиғи I чорак 2026 (1/4, НсО тўловчилари)",
    descRu: "Плательщики налога с оборота уплачивают авансовый платёж по земельному налогу за несельхозугодья за I квартал 2026 года (1/4 годовой суммы).",
    descEn: "Turnover tax payers pay the land tax advance for non-agricultural land for Q1 2026 (1/4 of annual amount).",
    descUz: "Aylanma soliq to'lovchilari 2026 yil I chorak uchun qishloq xo'jaligi maqsadlarida foydalanilmaydigan yerlar uchun yer solig'ini to'laydilar (1/4).",
    descUzc: "Айланма солиқ тўловчилари 2026 йил I чорак учун қишлоқ хўжалиги мақсадларида фойдаланилмайдиган ерлар учун ер солиғини тўлайдилар (1/4).",
    articleRef: "ст.432 ч.1 НК",
    orgTypes: LLC_JSC_IE,
    taxRegimes: TURNOVER_ONLY,
    requiresAssets: ["land_non_agri"],
    isPublished: true, isDraft: false,
  },

  // #24 Авансы имущество I кв 2026 (НсО, 1/4)
  {
    year: 2026, month: 3,
    date: new Date("2026-03-24"),
    originalDate: new Date("2026-03-20"),
    isPostponed: true,
    postponeReasonRu: "20 марта — Руза хайит, 21–23 марта — Навруз; срок переносится на 24 марта",
    postponeReasonEn: "March 20 — Ruza Hayit, March 21–23 — Navruz holidays; deadline moved to March 24",
    postponeReasonUz: "20 mart — Ro'za hayit, 21–23 mart — Navro'z; muddat 24 martga ko'chirildi",
    postponeReasonUzc: "20 март — Рўза ҳайит, 21–23 март — Навруз; муддат 24 мартга кўчирилди",
    taxType: TaxType.PROPERTY,
    eventType: EventType.PAYMENT,
    titleRu: "Авансы по налогу на имущество I кв 2026 (1/4, плательщики НсО)",
    titleEn: "Property tax advance Q1 2026 (1/4, turnover tax payers)",
    titleUz: "Mulk solig'i I chorak 2026 avans to'lovi (1/4, NsO to'lovchilari)",
    titleUzc: "Мулк солиғи I чорак 2026 аванс тўлови (1/4, НсО тўловчилари)",
    descRu: "Плательщики налога с оборота уплачивают авансовый платёж по налогу на имущество за I квартал 2026 года (1/4 годовой суммы).",
    descEn: "Turnover tax payers pay the property tax advance for Q1 2026 (1/4 of annual amount).",
    descUz: "Aylanma soliq to'lovchilari 2026 yil I chorak uchun mulk solig'i bo'yicha avans to'lovini amalga oshiradilar (1/4).",
    descUzc: "Айланма солиқ тўловчилари 2026 йил I чорак учун мулк солиғи бўйича аванс тўловини амалга оширадилар (1/4).",
    articleRef: "ст.417 ч.6 НК",
    orgTypes: LLC_JSC_IE,
    taxRegimes: TURNOVER_ONLY,
    requiresAssets: ["property"],
    isPublished: true, isDraft: false,
  },

  // #25 Отчётность по налогу с доходов нерезидентов за февраль 2026
  {
    year: 2026, month: 3,
    date: new Date("2026-03-24"),
    originalDate: new Date("2026-03-20"),
    isPostponed: true,
    postponeReasonRu: "20 марта — Руза хайит, 21–23 марта — Навруз; срок переносится на 24 марта",
    postponeReasonEn: "March 20 — Ruza Hayit, March 21–23 — Navruz holidays; deadline moved to March 24",
    postponeReasonUz: "20 mart — Ro'za hayit, 21–23 mart — Navro'z; muddat 24 martga ko'chirildi",
    postponeReasonUzc: "20 март — Рўза ҳайит, 21–23 март — Навруз; муддат 24 мартга кўчирилди",
    taxType: TaxType.PROFIT,
    eventType: EventType.REPORT,
    titleRu: "Отчётность по налогу с доходов нерезидентов за февраль 2026",
    titleEn: "Non-resident income tax reporting for February 2026",
    titleUz: "Fevral 2026 uchun norezidentlar daromadidan soliq hisoboti",
    titleUzc: "Феврал 2026 учун норезидентлар даромадидан солиқ ҳисоботи",
    descRu: "Налоговые агенты представляют отчётность по налогу с доходов нерезидентов за февраль 2026 года. Уплата: банки — до 5-го числа следующего месяца; остальные — день после выплаты дохода.",
    descEn: "Tax agents file non-resident income tax report for February 2026. Payment: banks by the 5th; others on the day after income payment.",
    descUz: "Soliq agentlari fevral 2026 uchun norezidentlar daromadidan soliq bo'yicha hisobot topshiradilar.",
    descUzc: "Солиқ агентлари феврал 2026 учун норезидентлар даромадидан солиқ бўйича ҳисобот топшириш.",
    articleRef: "ст.355 чч.1-2 НК",
    orgTypes: LLC_JSC,
    taxRegimes: VAT_TURNOVER,
    requiresSpecial: ["non_resident_income"],
    isPublished: true, isDraft: false,
  },

  // #26 Отчётность по налогу с дивидендов и процентов за февраль 2026
  {
    year: 2026, month: 3,
    date: new Date("2026-03-24"),
    originalDate: new Date("2026-03-20"),
    isPostponed: true,
    postponeReasonRu: "20 марта — Руза хайит, 21–23 марта — Навруз; срок переносится на 24 марта",
    postponeReasonEn: "March 20 — Ruza Hayit, March 21–23 — Navruz holidays; deadline moved to March 24",
    postponeReasonUz: "20 mart — Ro'za hayit, 21–23 mart — Navro'z; muddat 24 martga ko'chirildi",
    postponeReasonUzc: "20 март — Рўза ҳайит, 21–23 март — Навруз; муддат 24 мартга кўчирилди",
    taxType: TaxType.PROFIT,
    eventType: EventType.REPORT,
    titleRu: "Отчётность по налогу с дивидендов и процентов за февраль 2026",
    titleEn: "Dividend and interest tax reporting for February 2026",
    titleUz: "Fevral 2026 uchun dividendlar va foizlardan soliq hisoboti",
    titleUzc: "Феврал 2026 учун дивидендлар ва фоизлардан солиқ ҳисоботи",
    descRu: "Налоговые агенты представляют отчётность по налогу с дивидендов и процентов за февраль 2026 года. Уплата производится не позднее даты выплаты дивидендов/процентов.",
    descEn: "Tax agents file dividend and interest tax report for February 2026. Payment due no later than the date of payment of dividends/interest.",
    descUz: "Soliq agentlari fevral 2026 uchun dividendlar va foizlardan soliq bo'yicha hisobot topshiradilar.",
    descUzc: "Солиқ агентлари феврал 2026 учун дивидендлар ва фоизлардан солиқ бўйича ҳисобот топшириш.",
    articleRef: "ст.345 чч.5-6 НК",
    orgTypes: LLC_JSC,
    taxRegimes: VAT_TURNOVER,
    requiresSpecial: ["dividends"],
    isPublished: true, isDraft: false,
  },

  // #27 Налог за пользование недрами за февраль 2026
  {
    year: 2026, month: 3,
    date: new Date("2026-03-24"),
    originalDate: new Date("2026-03-20"),
    isPostponed: true,
    postponeReasonRu: "20 марта — Руза хайит, 21–23 марта — Навруз; срок переносится на 24 марта",
    postponeReasonEn: "March 20 — Ruza Hayit, March 21–23 — Navruz holidays; deadline moved to March 24",
    postponeReasonUz: "20 mart — Ro'za hayit, 21–23 mart — Navro'z; muddat 24 martga ko'chirildi",
    postponeReasonUzc: "20 март — Рўза ҳайит, 21–23 март — Навруз; муддат 24 мартга кўчирилди",
    taxType: TaxType.RENT,
    eventType: EventType.BOTH,
    titleRu: "Налог за пользование недрами за февраль 2026",
    titleEn: "Subsoil use tax for February 2026",
    titleUz: "Fevral 2026 uchun yer osti boyliklaridan foydalanish solig'i",
    titleUzc: "Феврал 2026 учун ер ости бойликларидан фойдаланиш солиғи",
    descRu: "Пользователи недр представляют отчётность и уплачивают налог за пользование недрами за февраль 2026 года. Плательщики НсО освобождены (ст.461 НК).",
    descEn: "Subsoil users file return and pay subsoil use tax for February 2026. Turnover tax payers are excluded (Art.461 Tax Code).",
    descUz: "Yer osti boyliklaridan foydalanuvchilar fevral 2026 uchun soliq hisoboti topshiradilar va to'laydilar.",
    descUzc: "Ер ости бойликларидан фойдаланувчилар феврал 2026 учун солиқ ҳисоботи топшириш ва тўлайдилар.",
    articleRef: "ст.454 чч.3-4 НК",
    orgTypes: LLC_JSC,
    taxRegimes: VAT_ONLY,
    requiresSpecial: ["subsoil"],
    isPublished: true, isDraft: false,
  },

  // #28 Исправление ошибок ККТ за февраль 2026 (плательщики НДС)
  {
    year: 2026, month: 3,
    date: new Date("2026-03-24"),
    originalDate: new Date("2026-03-20"),
    isPostponed: true,
    postponeReasonRu: "20 марта — Руза хайит, 21–23 марта — Навруз; срок переносится на 24 марта",
    postponeReasonEn: "March 20 — Ruza Hayit, March 21–23 — Navruz holidays; deadline moved to March 24",
    postponeReasonUz: "20 mart — Ro'za hayit, 21–23 mart — Navro'z; muddat 24 martga ko'chirildi",
    postponeReasonUzc: "20 март — Рўза ҳайит, 21–23 март — Навруз; муддат 24 мартга кўчирилди",
    taxType: TaxType.VAT,
    eventType: EventType.REPORT,
    titleRu: "Исправление ошибок ККТ за февраль 2026 (плательщики НДС)",
    titleEn: "Correction of online cash register errors for February 2026 (VAT payers)",
    titleUz: "Fevral 2026 uchun KKM xatolarini tuzatish (QQS to'lovchilari)",
    titleUzc: "Феврал 2026 учун ККМ хатоларини тузатиш (ҚҚС тўловчилари)",
    descRu: "Последний день исправления технических ошибок в чеках онлайн-ККТ за февраль 2026 года для плательщиков НДС.",
    descEn: "Last day to correct technical errors in online cash register receipts for February 2026 for VAT payers.",
    descUz: "QQS to'lovchilari uchun fevral 2026 bo'yicha onlayn-KKM cheklaridagi xatolarni tuzatishning oxirgi kuni.",
    descUzc: "ҚҚС тўловчилари учун феврал 2026 бўйича онлайн-ККМ чекларидаги хатоларни тузатишнинг охирги куни.",
    articleRef: "ПКМ №943 п.38-1, ст.273 НК",
    orgTypes: LLC_JSC_IE,
    taxRegimes: VAT_ONLY,
    requiresSpecial: ["online_kkt"],
    isPublished: true, isDraft: false,
  },

  // #29 Авансы по налогу на прибыль за март 2026 (>20 млрд)
  {
    year: 2026, month: 3,
    date: new Date("2026-03-24"),
    originalDate: new Date("2026-03-20"),
    isPostponed: true,
    postponeReasonRu: "20 марта — Руза хайит, 21–23 марта — Навруз; срок переносится на 24 марта",
    postponeReasonEn: "March 20 — Ruza Hayit, March 21–23 — Navruz holidays; deadline moved to March 24",
    postponeReasonUz: "20 mart — Ro'za hayit, 21–23 mart — Navro'z; muddat 24 martga ko'chirildi",
    postponeReasonUzc: "20 март — Рўза ҳайит, 21–23 март — Навруз; муддат 24 мартга кўчирилди",
    taxType: TaxType.PROFIT,
    eventType: EventType.PAYMENT,
    titleRu: "Авансовый платёж по налогу на прибыль за март 2026 (доход >20 млрд)",
    titleEn: "Profit tax advance payment for March 2026 (revenue >20 billion)",
    titleUz: "Mart 2026 uchun foyda solig'i bo'yicha avans to'lov (daromad >20 mlrd)",
    titleUzc: "Март 2026 учун фойда солиғи бўйича аванс тўлов (даромад >20 млрд)",
    descRu: "Юридические лица, чей совокупный доход за 2025 год превысил 20 млрд сум, уплачивают ежемесячный авансовый платёж по налогу на прибыль за март 2026 года.",
    descEn: "Legal entities with aggregate 2025 income exceeding 20 billion UZS pay the monthly profit tax advance for March 2026.",
    descUz: "2025 yil uchun yalpi daromadi 20 milliard so'mdan oshgan yuridik shaxslar mart 2026 uchun foyda solig'i bo'yicha oylik avans to'lovini amalga oshiradilar.",
    descUzc: "2025 йил учун ялпи даромади 20 миллиард сўмдан ошган юридик шахслар март 2026 учун фойда солиғи бўйича ойлик аванс тўловини амалга оширадилар.",
    articleRef: "ст.340 чч.2,7-8 НК",
    orgTypes: LLC_JSC,
    taxRegimes: VAT_ONLY,
    requiresSpecial: ["high_revenue_20b"],
    isPublished: true, isDraft: false,
  },

  // ─────────── 25 марта ───────────

  // #30 Возмещение расходов ПФ за февраль 2026
  {
    year: 2026, month: 3,
    date: new Date("2026-03-25"),
    taxType: TaxType.OTHER,
    eventType: EventType.PAYMENT,
    titleRu: "Возмещение расходов Пенсионного фонда за февраль 2026",
    titleEn: "Reimbursement of Pension Fund expenses for February 2026",
    titleUz: "Fevral 2026 uchun Pensiya jamg'armasi xarajatlarini qoplash",
    titleUzc: "Феврал 2026 учун Пенсия жамғармаси харажатларини қоплаш",
    descRu: "Работодатели перечисляют в Пенсионный фонд средства в возмещение расходов по выплаченным пенсиям (по потере кормильца, по инвалидности вследствие трудового увечья) за февраль 2026 года.",
    descEn: "Employers reimburse the Pension Fund for pensions paid (survivor's pension, disability due to work injury) for February 2026.",
    descUz: "Ish beruvchilar fevral 2026 uchun to'langan pensiyalar (boqimandalarni yo'qotish, mehnat jarohati tufayli nogironlik) bo'yicha Pensiya jamg'armasi xarajatlarini qoplash uchun mablag' o'tkazadilar.",
    descUzc: "Иш берувчилар феврал 2026 учун тўланган пенсиялар (боқимандаларни йўқотиш, меҳнат жароҳати туфайли ногиронлик) бўйича Пенсия жамғармаси харажатларини қоплаш учун маблағ ўтказадилар.",
    articleRef: "ПКМ №661 п.32",
    orgTypes: LLC_JSC_IE,
    taxRegimes: VAT_TURNOVER,
    requiresEmployees: true,
    requiresPension: ["loss_of_breadwinner"],
    isPublished: true, isDraft: false,
  },
];

async function main() {
  console.log("Seeding March 2026 events (spec-correct version)...");
  let created = 0;
  let skipped = 0;

  // First: remove old incorrect March 2026 events
  const deleted = await prisma.taxEvent.deleteMany({
    where: { year: 2026, month: 3 },
  });
  console.log(`Deleted ${deleted.count} existing March 2026 events.`);

  for (const event of events) {
    await prisma.taxEvent.create({ data: event as never });
    console.log(`  ✓ ${event.date.toISOString().slice(0, 10)} — ${event.titleRu.slice(0, 60)}`);
    created++;
  }

  console.log(`\nDone. Created: ${created}, Skipped: ${skipped}`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
