import { PrismaClient, TaxType, EventType, OrgType, TaxRegime } from "@prisma/client";
import bcrypt from "bcryptjs";

const prisma = new PrismaClient();

const events2025 = [
  // JANUARY
  {
    year: 2025, month: 1, date: new Date("2025-01-15"),
    taxType: TaxType.PROFIT, eventType: EventType.PAYMENT,
    titleRu: "Уплата налога на прибыль банками (нерезиденты, декабрь 2024)",
    titleEn: "Corporate income tax payment by banks (non-residents, December 2024)",
    titleUz: "Banklar tomonidan daromad solig'ini to'lash (norezidentlar, 2024 dekabr)",
    titleUzc: "Банклар томонидан даромад солиғини тўлаш (норезидентлар, 2024 декабрь)",
    descRu: "Последний день уплаты банками налога на прибыль по доходам, выплаченным нерезидентам (за исключением доходов в виде дивидендов и процентов) в декабре 2024 года.",
    descEn: "Last day for banks to pay corporate income tax on income paid to non-residents (except dividends and interest) in December 2024.",
    descUz: "Banklar tomonidan 2024 yil dekabr oyida norezidentlarga to'langan daromadlar (dividendlar va foizlardan tashqari) bo'yicha daromad solig'ini to'lashning oxirgi kuni.",
    descUzc: "Банклар томонидан 2024 йил декабрь ойида норезидентларга тўланган даромадлар (дивидендлар ва фоизлардан ташқари) бўйича даромад солиғини тўлашнинг охирги куни.",
    articleRef: "НК, ст. 355, ч. 2, п. 1",
    orgTypes: [OrgType.LLC, OrgType.JSC],
  },
  {
    year: 2025, month: 1, date: new Date("2025-01-20"),
    taxType: TaxType.VAT, eventType: EventType.BOTH,
    titleRu: "Отчётность и уплата НДС за декабрь 2024",
    titleEn: "VAT return and payment for December 2024",
    titleUz: "2024 yil dekabr uchun QQS hisoboti va to'lovi",
    titleUzc: "2024 йил декабрь учун ҚҚС ҳисоботи ва тўлови",
    descRu: "Последний день представления отчётности и уплаты налога на добавленную стоимость за декабрь 2024 года.",
    descEn: "Last day to file VAT return and pay VAT for December 2024.",
    descUz: "2024 yil dekabr uchun QQS bo'yicha hisobot topshirish va soliq to'lashning oxirgi kuni.",
    descUzc: "2024 йил декабрь учун ҚҚС бўйича ҳисобот топшириш ва солиқ тўлашнинг охирги куни.",
    articleRef: "НК, ст. 273, 274",
    taxRegimes: [TaxRegime.VAT],
  },
  {
    year: 2025, month: 1, date: new Date("2025-01-20"),
    taxType: TaxType.EXCISE, eventType: EventType.BOTH,
    titleRu: "Отчётность и уплата акцизного налога за декабрь 2024",
    titleEn: "Excise tax return and payment for December 2024",
    titleUz: "2024 yil dekabr uchun aksiz solig'i hisoboti va to'lovi",
    titleUzc: "2024 йил декабрь учун акциз солиғи ҳисоботи ва тўлови",
    descRu: "Последний день представления отчётности и уплаты акцизного налога за декабрь 2024 года.",
    descEn: "Last day to file excise tax return and pay excise tax for December 2024.",
    descUz: "2024 yil dekabr uchun aksiz solig'i bo'yicha hisobot topshirish va to'lashning oxirgi kuni.",
    descUzc: "2024 йил декабрь учун акциз солиғи бўйича ҳисобот топшириш ва тўлашнинг охирги куни.",
    articleRef: "НК, ст. 292, 293",
  },
  {
    year: 2025, month: 1, date: new Date("2025-01-15"),
    taxType: TaxType.SOCIAL, eventType: EventType.BOTH,
    titleRu: "Отчётность и уплата НДФЛ и социального налога за декабрь 2024",
    titleEn: "Personal income tax and social tax return for December 2024",
    titleUz: "2024 yil dekabr uchun JDST va ijtimoiy soliq hisoboti",
    titleUzc: "2024 йил декабрь учун ЖДСТ ва ижтимоий солиқ ҳисоботи",
    descRu: "Последний день представления отчётности и уплаты НДФЛ и социального налога за декабрь 2024 года.",
    descEn: "Last day to file personal income tax and social tax return and pay for December 2024.",
    descUz: "2024 yil dekabr uchun jismoniy shaxslardan daromad solig'i va ijtimoiy soliq bo'yicha hisobot topshirish va to'lashning oxirgi kuni.",
    descUzc: "2024 йил декабрь учун жисмоний шахслардан даромад солиғи ва ижтимоий солиқ бўйича ҳисобот топшириш ва тўлашнинг охирги куни.",
    articleRef: "НК, ст. 389, 390",
  },
  {
    year: 2025, month: 1, date: new Date("2025-01-15"),
    taxType: TaxType.TURNOVER, eventType: EventType.BOTH,
    titleRu: "Отчётность и уплата налога с оборота за декабрь 2024",
    titleEn: "Turnover tax return and payment for December 2024",
    titleUz: "2024 yil dekabr uchun aylanma solig'i hisoboti va to'lovi",
    titleUzc: "2024 йил декабрь учун айланма солиғи ҳисоботи ва тўлови",
    descRu: "Последний день представления отчётности и уплаты налога с оборота за декабрь 2024 года.",
    descEn: "Last day to file turnover tax return and pay turnover tax for December 2024.",
    descUz: "2024 yil dekabr uchun aylanma solig'i bo'yicha hisobot topshirish va to'lashning oxirgi kuni.",
    descUzc: "2024 йил декабрь учун айланма солиғи бўйича ҳисобот топшириш ва тўлашнинг охирги куни.",
    articleRef: "НК, ст. 464",
    taxRegimes: [TaxRegime.TURNOVER],
  },
  {
    year: 2025, month: 1, date: new Date("2025-01-20"),
    taxType: TaxType.INPS, eventType: EventType.BOTH,
    titleRu: "Уплата и реестры взносов ИНПС за декабрь 2024",
    titleEn: "INPS pension contributions and registers for December 2024",
    titleUz: "2024 yil dekabr uchun INPS badallari va reestrlari",
    titleUzc: "2024 йил декабрь учун ИНПС бадаллари ва реестрлари",
    descRu: "Последний день представления реестров и уплаты взносов на ИНПС (индивидуальные накопительные пенсионные счета) за декабрь 2024 года.",
    descEn: "Last day to submit registers and pay INPS (individual funded pension account) contributions for December 2024.",
    descUz: "2024 yil dekabr uchun INPS (individual jamg'arma pensiya hisobvarag'i) badallari rejestrlarini topshirish va to'lashning oxirgi kuni.",
    descUzc: "2024 йил декабрь учун ИНПС (индивидуал жамғарма пенсия ҳисобварағи) бадаллари рееструларини топшириш ва тўлашнинг охирги куни.",
    articleRef: "МЮ N 3577, п. 6, 9",
  },
  // FEBRUARY
  {
    year: 2025, month: 2, date: new Date("2025-02-20"),
    taxType: TaxType.VAT, eventType: EventType.BOTH,
    titleRu: "Отчётность и уплата НДС за январь 2025",
    titleEn: "VAT return and payment for January 2025",
    titleUz: "2025 yil yanvar uchun QQS hisoboti va to'lovi",
    titleUzc: "2025 йил январь учун ҚҚС ҳисоботи ва тўлови",
    descRu: "Последний день представления отчётности и уплаты налога на добавленную стоимость за январь 2025 года.",
    descEn: "Last day to file VAT return and pay VAT for January 2025.",
    descUz: "2025 yil yanvar uchun QQS bo'yicha hisobot topshirish va soliq to'lashning oxirgi kuni.",
    descUzc: "2025 йил январь учун ҚҚС бўйича ҳисобот топшириш ва солиқ тўлашнинг охирги куни.",
    articleRef: "НК, ст. 273, 274",
    taxRegimes: [TaxRegime.VAT],
  },
  {
    year: 2025, month: 2, date: new Date("2025-02-17"),
    taxType: TaxType.SOCIAL, eventType: EventType.BOTH,
    titleRu: "Отчётность и уплата НДФЛ и социального налога за январь 2025",
    titleEn: "Personal income tax and social tax return for January 2025",
    titleUz: "2025 yil yanvar uchun JDST va ijtimoiy soliq hisoboti",
    titleUzc: "2025 йил январь учун ЖДСТ ва ижтимоий солиқ ҳисоботи",
    descRu: "Последний день представления отчётности и уплаты НДФЛ и социального налога за январь 2025 года.",
    descEn: "Last day to file personal income tax and social tax return and pay for January 2025.",
    descUz: "2025 yil yanvar uchun jismoniy shaxslardan daromad solig'i va ijtimoiy soliq bo'yicha hisobot topshirish va to'lashning oxirgi kuni.",
    descUzc: "2025 йил январь учун жисмоний шахслардан даромад солиғи ва ижтимоий солиқ бўйича ҳисобот топшириш ва тўлашнинг охирги куни.",
    articleRef: "НК, ст. 389, 390",
  },
  {
    year: 2025, month: 2, date: new Date("2025-02-17"),
    taxType: TaxType.TURNOVER, eventType: EventType.BOTH,
    titleRu: "Отчётность и уплата налога с оборота за январь 2025",
    titleEn: "Turnover tax return and payment for January 2025",
    titleUz: "2025 yil yanvar uchun aylanma solig'i hisoboti",
    titleUzc: "2025 йил январь учун айланма солиғи ҳисоботи",
    descRu: "Последний день представления отчётности и уплаты налога с оборота за январь 2025 года.",
    descEn: "Last day to file turnover tax return and pay for January 2025.",
    descUz: "2025 yil yanvar uchun aylanma solig'i bo'yicha hisobot topshirish va to'lashning oxirgi kuni.",
    descUzc: "2025 йил январь учун айланма солиғи бўйича ҳисобот топшириш ва тўлашнинг охирги куни.",
    articleRef: "НК, ст. 464",
    taxRegimes: [TaxRegime.TURNOVER],
  },
  {
    year: 2025, month: 2, date: new Date("2025-02-20"),
    taxType: TaxType.PROPERTY, eventType: EventType.PAYMENT,
    titleRu: "Авансовый платёж по налогу на имущество за февраль 2025",
    titleEn: "Property tax advance payment for February 2025",
    titleUz: "2025 yil fevral uchun mulk solig'i bo'yicha avans to'lovi",
    titleUzc: "2025 йил февраль учун мулк солиғи бўйича аванс тўлови",
    descRu: "Последний день уплаты авансовых платежей по налогу на имущество за февраль 2025 года (для налогоплательщиков, не уплачивающих налог с оборота) — в размере 1/12 части годовой суммы налога.",
    descEn: "Last day for property tax advance payment for February 2025 (for taxpayers not paying turnover tax) — 1/12 of the annual tax amount.",
    descUz: "2025 yil fevral uchun mulk solig'i bo'yicha avans to'lovini amalga oshirishning oxirgi kuni (aylanma soliq to'lamaydigan soliq to'lovchilar uchun) — yillik soliq summasining 1/12 qismi.",
    descUzc: "2025 йил февраль учун мулк солиғи бўйича аванс тўловини амалга оширишнинг охирги куни (айланма солиқ тўламайдиган солиқ тўловчилар учун) — йиллик солиқ суммасининг 1/12 қисми.",
    articleRef: "НК, ст. 417, ч. 6",
    taxRegimes: [TaxRegime.VAT],
  },
  // MARCH
  {
    year: 2025, month: 3, date: new Date("2025-03-20"),
    taxType: TaxType.VAT, eventType: EventType.BOTH,
    titleRu: "Отчётность и уплата НДС за февраль 2025",
    titleEn: "VAT return and payment for February 2025",
    titleUz: "2025 yil fevral uchun QQS hisoboti va to'lovi",
    titleUzc: "2025 йил февраль учун ҚҚС ҳисоботи ва тўлови",
    descRu: "Последний день представления отчётности и уплаты НДС за февраль 2025 года.",
    descEn: "Last day to file VAT return and pay VAT for February 2025.",
    descUz: "2025 yil fevral uchun QQS bo'yicha hisobot topshirish va soliq to'lashning oxirgi kuni.",
    descUzc: "2025 йил февраль учун ҚҚС бўйича ҳисобот топшириш ва солиқ тўлашнинг охирги куни.",
    articleRef: "НК, ст. 273, 274",
    taxRegimes: [TaxRegime.VAT],
  },
  {
    year: 2025, month: 3, date: new Date("2025-03-20"),
    taxType: TaxType.PROFIT, eventType: EventType.PAYMENT,
    titleRu: "Авансовый платёж по налогу на прибыль за 1 квартал 2025",
    titleEn: "Corporate income tax advance payment for Q1 2025",
    titleUz: "2025 yil 1-chorak uchun daromad solig'i avans to'lovi",
    titleUzc: "2025 йил 1-чорак учун даромад солиғи аванс тўлови",
    descRu: "Последний день уплаты авансового платежа по налогу на прибыль за I квартал 2025 года.",
    descEn: "Last day to pay corporate income tax advance payment for Q1 2025.",
    descUz: "2025 yil I chorak uchun daromad solig'i bo'yicha avans to'lovini amalga oshirishning oxirgi kuni.",
    descUzc: "2025 йил I чорак учун даромад солиғи бўйича аванс тўловини амалга оширишнинг охирги куни.",
    articleRef: "НК, ст. 351",
    orgTypes: [OrgType.LLC, OrgType.JSC],
    taxRegimes: [TaxRegime.VAT],
  },
  {
    year: 2025, month: 3, date: new Date("2025-03-17"),
    taxType: TaxType.SOCIAL, eventType: EventType.BOTH,
    titleRu: "Отчётность и уплата НДФЛ и социального налога за февраль 2025",
    titleEn: "Personal income tax and social tax for February 2025",
    titleUz: "2025 yil fevral uchun JDST va ijtimoiy soliq",
    titleUzc: "2025 йил февраль учун ЖДСТ ва ижтимоий солиқ",
    descRu: "Последний день представления отчётности и уплаты НДФЛ и социального налога за февраль 2025 года.",
    descEn: "Last day to file and pay personal income tax and social tax for February 2025.",
    descUz: "2025 yil fevral uchun JDST va ijtimoiy soliq bo'yicha hisobot topshirish va to'lashning oxirgi kuni.",
    descUzc: "2025 йил февраль учун ЖДСТ ва ижтимоий солиқ бўйича ҳисобот топшириш ва тўлашнинг охирги куни.",
    articleRef: "НК, ст. 389, 390",
  },
  {
    year: 2025, month: 3, date: new Date("2025-03-17"),
    taxType: TaxType.TURNOVER, eventType: EventType.BOTH,
    titleRu: "Отчётность и уплата налога с оборота за февраль 2025",
    titleEn: "Turnover tax return and payment for February 2025",
    titleUz: "2025 yil fevral uchun aylanma solig'i hisoboti va to'lovi",
    titleUzc: "2025 йил февраль учун айланма солиғи ҳисоботи ва тўлови",
    descRu: "Последний день представления отчётности и уплаты налога с оборота за февраль 2025 года.",
    descEn: "Last day to file turnover tax return and pay turnover tax for February 2025.",
    descUz: "2025 yil fevral uchun aylanma solig'i bo'yicha hisobot topshirish va to'lashning oxirgi kuni.",
    descUzc: "2025 йил февраль учун айланма солиғи бўйича ҳисобот топшириш ва тўлашнинг охирги куни.",
    articleRef: "НК, ст. 464",
    taxRegimes: [TaxRegime.TURNOVER],
  },
  {
    year: 2025, month: 3, date: new Date("2025-03-20"),
    taxType: TaxType.PROPERTY, eventType: EventType.PAYMENT,
    titleRu: "Авансовый платёж по налогу на имущество за 1 квартал (оборотный режим)",
    titleEn: "Property tax advance payment for Q1 2025 (turnover tax regime)",
    titleUz: "2025 yil 1-chorak uchun mulk solig'i avans to'lovi (aylanma soliq rejimi)",
    titleUzc: "2025 йил 1-чорак учун мулк солиғи аванс тўлови (айланма солиқ режими)",
    descRu: "Последний день уплаты авансовых платежей по налогу на имущество за I квартал для плательщиков налога с оборота в размере 1/4 части годовой суммы налога.",
    descEn: "Last day for turnover tax payers to pay property tax advance for Q1 2025 — 1/4 of the annual tax amount.",
    descUz: "Aylanma soliq to'lovchilari uchun 2025 yil I chorak uchun mulk solig'i avansini to'lashning oxirgi kuni — yillik soliq summasining 1/4 qismi.",
    descUzc: "Айланма солиқ тўловчилари учун 2025 йил I чорак учун мулк солиғи авансини тўлашнинг охирги куни — йиллик солиқ суммасининг 1/4 қисми.",
    articleRef: "НК, ст. 417, ч. 6",
    taxRegimes: [TaxRegime.TURNOVER],
  },
  // APRIL
  {
    year: 2025, month: 4, date: new Date("2025-04-01"),
    taxType: TaxType.PROFIT, eventType: EventType.BOTH,
    titleRu: "Годовая декларация по налогу на прибыль за 2024 год",
    titleEn: "Annual corporate income tax return for 2024",
    titleUz: "2024 yil uchun yillik daromad solig'i deklaratsiyasi",
    titleUzc: "2024 йил учун йиллик даромад солиғи декларацияси",
    descRu: "Последний день представления годовой декларации и уплаты налога на прибыль за 2024 год.",
    descEn: "Last day to file annual corporate income tax return and pay tax for 2024.",
    descUz: "2024 yil uchun yillik daromad solig'i deklaratsiyasini topshirish va to'lashning oxirgi kuni.",
    descUzc: "2024 йил учун йиллик даромад солиғи декларациясини топшириш ва тўлашнинг охирги куни.",
    articleRef: "НК, ст. 352, ч. 1",
    orgTypes: [OrgType.LLC, OrgType.JSC],
    taxRegimes: [TaxRegime.VAT],
  },
  {
    year: 2025, month: 4, date: new Date("2025-04-20"),
    taxType: TaxType.VAT, eventType: EventType.BOTH,
    titleRu: "Отчётность и уплата НДС за март 2025",
    titleEn: "VAT return and payment for March 2025",
    titleUz: "2025 yil mart uchun QQS hisoboti va to'lovi",
    titleUzc: "2025 йил март учун ҚҚС ҳисоботи ва тўлови",
    descRu: "Последний день представления отчётности и уплаты НДС за март 2025 года.",
    descEn: "Last day to file VAT return and pay VAT for March 2025.",
    descUz: "2025 yil mart uchun QQS bo'yicha hisobot topshirish va soliq to'lashning oxirgi kuni.",
    descUzc: "2025 йил март учун ҚҚС бўйича ҳисобот топшириш ва солиқ тўлашнинг охирги куни.",
    articleRef: "НК, ст. 273, 274",
    taxRegimes: [TaxRegime.VAT],
  },
  {
    year: 2025, month: 4, date: new Date("2025-04-15"),
    taxType: TaxType.SOCIAL, eventType: EventType.BOTH,
    titleRu: "Отчётность и уплата НДФЛ и социального налога за март 2025",
    titleEn: "Personal income tax and social tax for March 2025",
    titleUz: "2025 yil mart uchun JDST va ijtimoiy soliq",
    titleUzc: "2025 йил март учун ЖДСТ ва ижтимоий солиқ",
    descRu: "Последний день представления отчётности и уплаты НДФЛ и социального налога за март 2025 года.",
    descEn: "Last day to file and pay personal income tax and social tax for March 2025.",
    descUz: "2025 yil mart uchun JDST va ijtimoiy soliq bo'yicha hisobot topshirish va to'lashning oxirgi kuni.",
    descUzc: "2025 йил март учун ЖДСТ ва ижтимоий солиқ бўйича ҳисобот топшириш ва тўлашнинг охирги куни.",
    articleRef: "НК, ст. 389, 390",
  },
  {
    year: 2025, month: 4, date: new Date("2025-04-15"),
    taxType: TaxType.TURNOVER, eventType: EventType.BOTH,
    titleRu: "Отчётность и уплата налога с оборота за март 2025",
    titleEn: "Turnover tax return and payment for March 2025",
    titleUz: "2025 yil mart uchun aylanma solig'i hisoboti va to'lovi",
    titleUzc: "2025 йил март учун айланма солиғи ҳисоботи ва тўлови",
    descRu: "Последний день представления отчётности и уплаты налога с оборота за март 2025 года.",
    descEn: "Last day to file turnover tax return and pay turnover tax for March 2025.",
    descUz: "2025 yil mart uchun aylanma solig'i bo'yicha hisobot topshirish va to'lashning oxirgi kuni.",
    descUzc: "2025 йил март учун айланма солиғи бўйича ҳисобот топшириш ва тўлашнинг охирги куни.",
    articleRef: "НК, ст. 464",
    taxRegimes: [TaxRegime.TURNOVER],
  },
  // MAY
  {
    year: 2025, month: 5, date: new Date("2025-05-20"),
    taxType: TaxType.VAT, eventType: EventType.BOTH,
    titleRu: "Отчётность и уплата НДС за апрель 2025",
    titleEn: "VAT return and payment for April 2025",
    titleUz: "2025 yil aprel uchun QQS hisoboti va to'lovi",
    titleUzc: "2025 йил апрель учун ҚҚС ҳисоботи ва тўлови",
    descRu: "Последний день представления отчётности и уплаты НДС за апрель 2025 года.",
    descEn: "Last day to file VAT return and pay VAT for April 2025.",
    descUz: "2025 yil aprel uchun QQS bo'yicha hisobot topshirish va soliq to'lashning oxirgi kuni.",
    descUzc: "2025 йил апрель учун ҚҚС бўйича ҳисобот топшириш ва солиқ тўлашнинг охирги куни.",
    articleRef: "НК, ст. 273, 274",
    taxRegimes: [TaxRegime.VAT],
  },
  {
    year: 2025, month: 5, date: new Date("2025-05-15"),
    taxType: TaxType.SOCIAL, eventType: EventType.BOTH,
    titleRu: "Отчётность и уплата НДФЛ и социального налога за апрель 2025",
    titleEn: "Personal income tax and social tax for April 2025",
    titleUz: "2025 yil aprel uchun JDST va ijtimoiy soliq",
    titleUzc: "2025 йил апрель учун ЖДСТ ва ижтимоий солиқ",
    descRu: "Последний день представления отчётности и уплаты НДФЛ и социального налога за апрель 2025 года.",
    descEn: "Last day to file and pay personal income tax and social tax for April 2025.",
    descUz: "2025 yil aprel uchun JDST va ijtimoiy soliq bo'yicha hisobot topshirish va to'lashning oxirgi kuni.",
    descUzc: "2025 йил апрель учун ЖДСТ ва ижтимоий солиқ бўйича ҳисобот топшириш ва тўлашнинг охирги куни.",
    articleRef: "НК, ст. 389, 390",
  },
  {
    year: 2025, month: 5, date: new Date("2025-05-15"),
    taxType: TaxType.TURNOVER, eventType: EventType.BOTH,
    titleRu: "Отчётность и уплата налога с оборота за апрель 2025",
    titleEn: "Turnover tax return and payment for April 2025",
    titleUz: "2025 yil aprel uchun aylanma solig'i hisoboti va to'lovi",
    titleUzc: "2025 йил апрель учун айланма солиғи ҳисоботи ва тўлови",
    descRu: "Последний день представления отчётности и уплаты налога с оборота за апрель 2025 года.",
    descEn: "Last day to file turnover tax return and pay turnover tax for April 2025.",
    descUz: "2025 yil aprel uchun aylanma solig'i bo'yicha hisobot topshirish va to'lashning oxirgi kuni.",
    descUzc: "2025 йил апрель учун айланма солиғи бўйича ҳисобот топшириш ва тўлашнинг охирги куни.",
    articleRef: "НК, ст. 464",
    taxRegimes: [TaxRegime.TURNOVER],
  },
  // JUNE
  {
    year: 2025, month: 6, date: new Date("2025-06-20"),
    taxType: TaxType.VAT, eventType: EventType.BOTH,
    titleRu: "Отчётность и уплата НДС за май 2025",
    titleEn: "VAT return and payment for May 2025",
    titleUz: "2025 yil may uchun QQS hisoboti va to'lovi",
    titleUzc: "2025 йил май учун ҚҚС ҳисоботи ва тўлови",
    descRu: "Последний день представления отчётности и уплаты НДС за май 2025 года.",
    descEn: "Last day to file VAT return and pay VAT for May 2025.",
    descUz: "2025 yil may uchun QQS bo'yicha hisobot topshirish va soliq to'lashning oxirgi kuni.",
    descUzc: "2025 йил май учун ҚҚС бўйича ҳисобот топшириш ва солиқ тўлашнинг охирги куни.",
    articleRef: "НК, ст. 273, 274",
    taxRegimes: [TaxRegime.VAT],
  },
  {
    year: 2025, month: 6, date: new Date("2025-06-20"),
    taxType: TaxType.PROFIT, eventType: EventType.PAYMENT,
    titleRu: "Авансовый платёж по налогу на прибыль за 2 квартал 2025",
    titleEn: "Corporate income tax advance for Q2 2025",
    titleUz: "2025 yil 2-chorak uchun daromad solig'i avans to'lovi",
    titleUzc: "2025 йил 2-чорак учун даромад солиғи аванс тўлови",
    descRu: "Последний день уплаты авансового платежа по налогу на прибыль за II квартал 2025 года.",
    descEn: "Last day to pay corporate income tax advance for Q2 2025.",
    descUz: "2025 yil II chorak uchun daromad solig'i bo'yicha avans to'lovini amalga oshirishning oxirgi kuni.",
    descUzc: "2025 йил II чорак учун даромад солиғи бўйича аванс тўловини амалга оширишнинг охирги куни.",
    articleRef: "НК, ст. 351",
    orgTypes: [OrgType.LLC, OrgType.JSC],
    taxRegimes: [TaxRegime.VAT],
  },
  {
    year: 2025, month: 6, date: new Date("2025-06-16"),
    taxType: TaxType.SOCIAL, eventType: EventType.BOTH,
    titleRu: "Отчётность и уплата НДФЛ и социального налога за май 2025",
    titleEn: "Personal income tax and social tax for May 2025",
    titleUz: "2025 yil may uchun JDST va ijtimoiy soliq",
    titleUzc: "2025 йил май учун ЖДСТ ва ижтимоий солиқ",
    descRu: "Последний день представления отчётности и уплаты НДФЛ и социального налога за май 2025 года.",
    descEn: "Last day to file and pay personal income tax and social tax for May 2025.",
    descUz: "2025 yil may uchun JDST va ijtimoiy soliq bo'yicha hisobot topshirish va to'lashning oxirgi kuni.",
    descUzc: "2025 йил май учун ЖДСТ ва ижтимоий солиқ бўйича ҳисобот топшириш ва тўлашнинг охирги куни.",
    articleRef: "НК, ст. 389, 390",
  },
  {
    year: 2025, month: 6, date: new Date("2025-06-16"),
    taxType: TaxType.TURNOVER, eventType: EventType.BOTH,
    titleRu: "Отчётность и уплата налога с оборота за май 2025",
    titleEn: "Turnover tax return and payment for May 2025",
    titleUz: "2025 yil may uchun aylanma solig'i hisoboti va to'lovi",
    titleUzc: "2025 йил май учун айланма солиғи ҳисоботи ва тўлови",
    descRu: "Последний день представления отчётности и уплаты налога с оборота за май 2025 года.",
    descEn: "Last day to file turnover tax return and pay turnover tax for May 2025.",
    descUz: "2025 yil may uchun aylanma solig'i bo'yicha hisobot topshirish va to'lashning oxirgi kuni.",
    descUzc: "2025 йил май учун айланма солиғи бўйича ҳисобот топшириш ва тўлашнинг охирги куни.",
    articleRef: "НК, ст. 464",
    taxRegimes: [TaxRegime.TURNOVER],
  },
  // JULY
  {
    year: 2025, month: 7, date: new Date("2025-07-20"),
    taxType: TaxType.VAT, eventType: EventType.BOTH,
    titleRu: "Отчётность и уплата НДС за июнь 2025",
    titleEn: "VAT return and payment for June 2025",
    titleUz: "2025 yil iyun uchun QQS hisoboti va to'lovi",
    titleUzc: "2025 йил июнь учун ҚҚС ҳисоботи ва тўлови",
    descRu: "Последний день представления отчётности и уплаты НДС за июнь 2025 года.",
    descEn: "Last day to file VAT return and pay VAT for June 2025.",
    descUz: "2025 yil iyun uchun QQS bo'yicha hisobot topshirish va soliq to'lashning oxirgi kuni.",
    descUzc: "2025 йил июнь учун ҚҚС бўйича ҳисобот топшириш ва солиқ тўлашнинг охирги куни.",
    articleRef: "НК, ст. 273, 274",
    taxRegimes: [TaxRegime.VAT],
  },
  {
    year: 2025, month: 7, date: new Date("2025-07-15"),
    taxType: TaxType.TURNOVER, eventType: EventType.BOTH,
    titleRu: "Отчётность и уплата налога с оборота за июнь 2025",
    titleEn: "Turnover tax return and payment for June 2025",
    titleUz: "2025 yil iyun uchun aylanma solig'i hisoboti va to'lovi",
    titleUzc: "2025 йил июнь учун айланма солиғи ҳисоботи ва тўлови",
    descRu: "Последний день представления отчётности и уплаты налога с оборота за июнь 2025 года.",
    descEn: "Last day to file turnover tax return and pay turnover tax for June 2025.",
    descUz: "2025 yil iyun uchun aylanma solig'i bo'yicha hisobot topshirish va to'lashning oxirgi kuni.",
    descUzc: "2025 йил июнь учун айланма солиғи бўйича ҳисобот топшириш ва тўлашнинг охирги куни.",
    articleRef: "НК, ст. 464",
    taxRegimes: [TaxRegime.TURNOVER],
  },
  {
    year: 2025, month: 7, date: new Date("2025-07-15"),
    taxType: TaxType.SOCIAL, eventType: EventType.BOTH,
    titleRu: "Отчётность и уплата НДФЛ и социального налога за июнь 2025",
    titleEn: "Personal income tax and social tax for June 2025",
    titleUz: "2025 yil iyun uchun JDST va ijtimoiy soliq",
    titleUzc: "2025 йил июнь учун ЖДСТ ва ижтимоий солиқ",
    descRu: "Последний день представления отчётности и уплаты НДФЛ и социального налога за июнь 2025 года.",
    descEn: "Last day to file and pay personal income tax and social tax for June 2025.",
    descUz: "2025 yil iyun uchun JDST va ijtimoiy soliq bo'yicha hisobot topshirish va to'lashning oxirgi kuni.",
    descUzc: "2025 йил июнь учун ЖДСТ ва ижтимоий солиқ бўйича ҳисобот топшириш ва тўлашнинг охирги куни.",
    articleRef: "НК, ст. 389, 390",
  },
  // AUGUST
  {
    year: 2025, month: 8, date: new Date("2025-08-20"),
    taxType: TaxType.VAT, eventType: EventType.BOTH,
    titleRu: "Отчётность и уплата НДС за июль 2025",
    titleEn: "VAT return and payment for July 2025",
    titleUz: "2025 yil iyul uchun QQS hisoboti va to'lovi",
    titleUzc: "2025 йил июль учун ҚҚС ҳисоботи ва тўлови",
    descRu: "Последний день представления отчётности и уплаты НДС за июль 2025 года.",
    descEn: "Last day to file VAT return and pay VAT for July 2025.",
    descUz: "2025 yil iyul uchun QQS bo'yicha hisobot topshirish va soliq to'lashning oxirgi kuni.",
    descUzc: "2025 йил июль учун ҚҚС бўйича ҳисобот топшириш ва солиқ тўлашнинг охирги куни.",
    articleRef: "НК, ст. 273, 274",
    taxRegimes: [TaxRegime.VAT],
  },
  {
    year: 2025, month: 8, date: new Date("2025-08-20"),
    taxType: TaxType.PROFIT, eventType: EventType.PAYMENT,
    titleRu: "Авансовый платёж по налогу на прибыль за 3 квартал 2025",
    titleEn: "Corporate income tax advance for Q3 2025",
    titleUz: "2025 yil 3-chorak uchun daromad solig'i avans to'lovi",
    titleUzc: "2025 йил 3-чорак учун даромад солиғи аванс тўлови",
    descRu: "Последний день уплаты авансового платежа по налогу на прибыль за III квартал 2025 года.",
    descEn: "Last day to pay corporate income tax advance for Q3 2025.",
    descUz: "2025 yil III chorak uchun daromad solig'i bo'yicha avans to'lovini amalga oshirishning oxirgi kuni.",
    descUzc: "2025 йил III чорак учун даромад солиғи бўйича аванс тўловини амалга оширишнинг охирги куни.",
    articleRef: "НК, ст. 351",
    orgTypes: [OrgType.LLC, OrgType.JSC],
    taxRegimes: [TaxRegime.VAT],
  },
  {
    year: 2025, month: 8, date: new Date("2025-08-15"),
    taxType: TaxType.SOCIAL, eventType: EventType.BOTH,
    titleRu: "Отчётность и уплата НДФЛ и социального налога за июль 2025",
    titleEn: "Personal income tax and social tax for July 2025",
    titleUz: "2025 yil iyul uchun JDST va ijtimoiy soliq",
    titleUzc: "2025 йил июль учун ЖДСТ ва ижтимоий солиқ",
    descRu: "Последний день представления отчётности и уплаты НДФЛ и социального налога за июль 2025 года.",
    descEn: "Last day to file and pay personal income tax and social tax for July 2025.",
    descUz: "2025 yil iyul uchun JDST va ijtimoiy soliq bo'yicha hisobot topshirish va to'lashning oxirgi kuni.",
    descUzc: "2025 йил июль учун ЖДСТ ва ижтимоий солиқ бўйича ҳисобот топшириш ва тўлашнинг охирги куни.",
    articleRef: "НК, ст. 389, 390",
  },
  {
    year: 2025, month: 8, date: new Date("2025-08-15"),
    taxType: TaxType.TURNOVER, eventType: EventType.BOTH,
    titleRu: "Отчётность и уплата налога с оборота за июль 2025",
    titleEn: "Turnover tax return and payment for July 2025",
    titleUz: "2025 yil iyul uchun aylanma solig'i hisoboti va to'lovi",
    titleUzc: "2025 йил июль учун айланма солиғи ҳисоботи ва тўлови",
    descRu: "Последний день представления отчётности и уплаты налога с оборота за июль 2025 года.",
    descEn: "Last day to file turnover tax return and pay turnover tax for July 2025.",
    descUz: "2025 yil iyul uchun aylanma solig'i bo'yicha hisobot topshirish va to'lashning oxirgi kuni.",
    descUzc: "2025 йил июль учун айланма солиғи бўйича ҳисобот топшириш ва тўлашнинг охирги куни.",
    articleRef: "НК, ст. 464",
    taxRegimes: [TaxRegime.TURNOVER],
  },
  // SEPTEMBER
  {
    year: 2025, month: 9, date: new Date("2025-09-20"),
    taxType: TaxType.VAT, eventType: EventType.BOTH,
    titleRu: "Отчётность и уплата НДС за август 2025",
    titleEn: "VAT return and payment for August 2025",
    titleUz: "2025 yil avgust uchun QQS hisoboti va to'lovi",
    titleUzc: "2025 йил август учун ҚҚС ҳисоботи ва тўлови",
    descRu: "Последний день представления отчётности и уплаты НДС за август 2025 года.",
    descEn: "Last day to file VAT return and pay VAT for August 2025.",
    descUz: "2025 yil avgust uchun QQS bo'yicha hisobot topshirish va soliq to'lashning oxirgi kuni.",
    descUzc: "2025 йил август учун ҚҚС бўйича ҳисобот топшириш ва солиқ тўлашнинг охирги куни.",
    articleRef: "НК, ст. 273, 274",
    taxRegimes: [TaxRegime.VAT],
  },
  {
    year: 2025, month: 9, date: new Date("2025-09-15"),
    taxType: TaxType.TURNOVER, eventType: EventType.BOTH,
    titleRu: "Отчётность и уплата налога с оборота за август 2025",
    titleEn: "Turnover tax return and payment for August 2025",
    titleUz: "2025 yil avgust uchun aylanma solig'i hisoboti va to'lovi",
    titleUzc: "2025 йил август учун айланма солиғи ҳисоботи ва тўлови",
    descRu: "Последний день представления отчётности и уплаты налога с оборота за август 2025 года.",
    descEn: "Last day to file turnover tax return and pay turnover tax for August 2025.",
    descUz: "2025 yil avgust uchun aylanma solig'i bo'yicha hisobot topshirish va to'lashning oxirgi kuni.",
    descUzc: "2025 йил август учун айланма солиғи бўйича ҳисобот топшириш ва тўлашнинг охирги куни.",
    articleRef: "НК, ст. 464",
    taxRegimes: [TaxRegime.TURNOVER],
  },
  {
    year: 2025, month: 9, date: new Date("2025-09-15"),
    taxType: TaxType.SOCIAL, eventType: EventType.BOTH,
    titleRu: "Отчётность и уплата НДФЛ и социального налога за август 2025",
    titleEn: "Personal income tax and social tax for August 2025",
    titleUz: "2025 yil avgust uchun JDST va ijtimoiy soliq",
    titleUzc: "2025 йил август учун ЖДСТ ва ижтимоий солиқ",
    descRu: "Последний день представления отчётности и уплаты НДФЛ и социального налога за август 2025 года.",
    descEn: "Last day to file and pay personal income tax and social tax for August 2025.",
    descUz: "2025 yil avgust uchun JDST va ijtimoiy soliq bo'yicha hisobot topshirish va to'lashning oxirgi kuni.",
    descUzc: "2025 йил август учун ЖДСТ ва ижтимоий солиқ бўйича ҳисобот топшириш ва тўлашнинг охирги куни.",
    articleRef: "НК, ст. 389, 390",
  },
  // OCTOBER
  {
    year: 2025, month: 10, date: new Date("2025-10-20"),
    taxType: TaxType.VAT, eventType: EventType.BOTH,
    titleRu: "Отчётность и уплата НДС за сентябрь 2025",
    titleEn: "VAT return and payment for September 2025",
    titleUz: "2025 yil sentabr uchun QQS hisoboti va to'lovi",
    titleUzc: "2025 йил сентябрь учун ҚҚС ҳисоботи ва тўлови",
    descRu: "Последний день представления отчётности и уплаты НДС за сентябрь 2025 года.",
    descEn: "Last day to file VAT return and pay VAT for September 2025.",
    descUz: "2025 yil sentabr uchun QQS bo'yicha hisobot topshirish va soliq to'lashning oxirgi kuni.",
    descUzc: "2025 йил сентябрь учун ҚҚС бўйича ҳисобот топшириш ва солиқ тўлашнинг охирги куни.",
    articleRef: "НК, ст. 273, 274",
    taxRegimes: [TaxRegime.VAT],
  },
  {
    year: 2025, month: 10, date: new Date("2025-10-20"),
    taxType: TaxType.PROFIT, eventType: EventType.PAYMENT,
    titleRu: "Авансовый платёж по налогу на прибыль за 4 квартал 2025",
    titleEn: "Corporate income tax advance for Q4 2025",
    titleUz: "2025 yil 4-chorak uchun daromad solig'i avans to'lovi",
    titleUzc: "2025 йил 4-чорак учун даромад солиғи аванс тўлови",
    descRu: "Последний день уплаты авансового платежа по налогу на прибыль за IV квартал 2025 года.",
    descEn: "Last day to pay corporate income tax advance for Q4 2025.",
    descUz: "2025 yil IV chorak uchun daromad solig'i bo'yicha avans to'lovini amalga oshirishning oxirgi kuni.",
    descUzc: "2025 йил IV чорак учун даромад солиғи бўйича аванс тўловини амалга оширишнинг охирги куни.",
    articleRef: "НК, ст. 351",
    orgTypes: [OrgType.LLC, OrgType.JSC],
    taxRegimes: [TaxRegime.VAT],
  },
  {
    year: 2025, month: 10, date: new Date("2025-10-15"),
    taxType: TaxType.SOCIAL, eventType: EventType.BOTH,
    titleRu: "Отчётность и уплата НДФЛ и социального налога за сентябрь 2025",
    titleEn: "Personal income tax and social tax for September 2025",
    titleUz: "2025 yil sentabr uchun JDST va ijtimoiy soliq",
    titleUzc: "2025 йил сентябрь учун ЖДСТ ва ижтимоий солиқ",
    descRu: "Последний день представления отчётности и уплаты НДФЛ и социального налога за сентябрь 2025 года.",
    descEn: "Last day to file and pay personal income tax and social tax for September 2025.",
    descUz: "2025 yil sentabr uchun JDST va ijtimoiy soliq bo'yicha hisobot topshirish va to'lashning oxirgi kuni.",
    descUzc: "2025 йил сентябрь учун ЖДСТ ва ижтимоий солиқ бўйича ҳисобот топшириш ва тўлашнинг охирги куни.",
    articleRef: "НК, ст. 389, 390",
  },
  {
    year: 2025, month: 10, date: new Date("2025-10-15"),
    taxType: TaxType.TURNOVER, eventType: EventType.BOTH,
    titleRu: "Отчётность и уплата налога с оборота за сентябрь 2025",
    titleEn: "Turnover tax return and payment for September 2025",
    titleUz: "2025 yil sentabr uchun aylanma solig'i hisoboti va to'lovi",
    titleUzc: "2025 йил сентябрь учун айланма солиғи ҳисоботи ва тўлови",
    descRu: "Последний день представления отчётности и уплаты налога с оборота за сентябрь 2025 года.",
    descEn: "Last day to file turnover tax return and pay turnover tax for September 2025.",
    descUz: "2025 yil sentabr uchun aylanma solig'i bo'yicha hisobot topshirish va to'lashning oxirgi kuni.",
    descUzc: "2025 йил сентябрь учун айланма солиғи бўйича ҳисобот топшириш ва тўлашнинг охирги куни.",
    articleRef: "НК, ст. 464",
    taxRegimes: [TaxRegime.TURNOVER],
  },
  // NOVEMBER
  {
    year: 2025, month: 11, date: new Date("2025-11-20"),
    taxType: TaxType.VAT, eventType: EventType.BOTH,
    titleRu: "Отчётность и уплата НДС за октябрь 2025",
    titleEn: "VAT return and payment for October 2025",
    titleUz: "2025 yil oktabr uchun QQS hisoboti va to'lovi",
    titleUzc: "2025 йил октябрь учун ҚҚС ҳисоботи ва тўлови",
    descRu: "Последний день представления отчётности и уплаты НДС за октябрь 2025 года.",
    descEn: "Last day to file VAT return and pay VAT for October 2025.",
    descUz: "2025 yil oktabr uchun QQS bo'yicha hisobot topshirish va soliq to'lashning oxirgi kuni.",
    descUzc: "2025 йил октябрь учун ҚҚС бўйича ҳисобот топшириш ва солиқ тўлашнинг охирги куни.",
    articleRef: "НК, ст. 273, 274",
    taxRegimes: [TaxRegime.VAT],
  },
  {
    year: 2025, month: 11, date: new Date("2025-11-17"),
    taxType: TaxType.TURNOVER, eventType: EventType.BOTH,
    titleRu: "Отчётность и уплата налога с оборота за октябрь 2025",
    titleEn: "Turnover tax return and payment for October 2025",
    titleUz: "2025 yil oktabr uchun aylanma solig'i hisoboti va to'lovi",
    titleUzc: "2025 йил октябрь учун айланма солиғи ҳисоботи ва тўлови",
    descRu: "Последний день представления отчётности и уплаты налога с оборота за октябрь 2025 года.",
    descEn: "Last day to file turnover tax return and pay turnover tax for October 2025.",
    descUz: "2025 yil oktabr uchun aylanma solig'i bo'yicha hisobot topshirish va to'lashning oxirgi kuni.",
    descUzc: "2025 йил октябрь учун айланма солиғи бўйича ҳисобот топшириш ва тўлашнинг охирги куни.",
    articleRef: "НК, ст. 464",
    taxRegimes: [TaxRegime.TURNOVER],
  },
  {
    year: 2025, month: 11, date: new Date("2025-11-17"),
    taxType: TaxType.SOCIAL, eventType: EventType.BOTH,
    titleRu: "Отчётность и уплата НДФЛ и социального налога за октябрь 2025",
    titleEn: "Personal income tax and social tax for October 2025",
    titleUz: "2025 yil oktabr uchun JDST va ijtimoiy soliq",
    titleUzc: "2025 йил октябрь учун ЖДСТ ва ижтимоий солиқ",
    descRu: "Последний день представления отчётности и уплаты НДФЛ и социального налога за октябрь 2025 года.",
    descEn: "Last day to file and pay personal income tax and social tax for October 2025.",
    descUz: "2025 yil oktabr uchun JDST va ijtimoiy soliq bo'yicha hisobot topshirish va to'lashning oxirgi kuni.",
    descUzc: "2025 йил октябрь учун ЖДСТ ва ижтимоий солиқ бўйича ҳисобот топшириш ва тўлашнинг охирги куни.",
    articleRef: "НК, ст. 389, 390",
  },
  // DECEMBER
  {
    year: 2025, month: 12, date: new Date("2025-12-11"),
    taxType: TaxType.PROFIT, eventType: EventType.PAYMENT,
    titleRu: "Уплата налога на прибыль банками (нерезиденты, ноябрь 2025)",
    titleEn: "Corporate income tax payment by banks (non-residents, November 2025)",
    titleUz: "Banklar tomonidan daromad solig'ini to'lash (norezidentlar, 2025 noyabr)",
    titleUzc: "Банклар томонидан даромад солиғини тўлаш (норезидентлар, 2025 ноябрь)",
    descRu: "Последний день уплаты банками налога на прибыль по доходам, выплаченным нерезидентам (за исключением доходов в виде дивидендов и процентов) в ноябре 2025 года.",
    descEn: "Last day for banks to pay corporate income tax on income paid to non-residents in November 2025.",
    descUz: "Banklar tomonidan 2025 yil noyabr oyida norezidentlarga to'langan daromadlar bo'yicha daromad solig'ini to'lashning oxirgi kuni.",
    descUzc: "Банклар томонидан 2025 йил ноябрь ойида норезидентларга тўланган даромадлар бўйича даромад солиғини тўлашнинг охирги куни.",
    articleRef: "НК, ст. 355, ч. 2, п. 1",
    orgTypes: [OrgType.LLC, OrgType.JSC],
  },
  {
    year: 2025, month: 12, date: new Date("2025-12-20"),
    taxType: TaxType.VAT, eventType: EventType.BOTH,
    titleRu: "Отчётность и уплата НДС за ноябрь 2025",
    titleEn: "VAT return and payment for November 2025",
    titleUz: "2025 yil noyabr uchun QQS hisoboti va to'lovi",
    titleUzc: "2025 йил ноябрь учун ҚҚС ҳисоботи ва тўлови",
    descRu: "Последний день представления отчётности и уплаты НДС за ноябрь 2025 года.",
    descEn: "Last day to file VAT return and pay VAT for November 2025.",
    descUz: "2025 yil noyabr uchun QQS bo'yicha hisobot topshirish va soliq to'lashning oxirgi kuni.",
    descUzc: "2025 йил ноябрь учун ҚҚС бўйича ҳисобот топшириш ва солиқ тўлашнинг охирги куни.",
    articleRef: "НК, ст. 273, 274",
    taxRegimes: [TaxRegime.VAT],
  },
  {
    year: 2025, month: 12, date: new Date("2025-12-15"),
    taxType: TaxType.SOCIAL, eventType: EventType.BOTH,
    titleRu: "Отчётность и уплата НДФЛ и социального налога за ноябрь 2025",
    titleEn: "Personal income tax and social tax for November 2025",
    titleUz: "2025 yil noyabr uchun JDST va ijtimoiy soliq",
    titleUzc: "2025 йил ноябрь учун ЖДСТ ва ижтимоий солиқ",
    descRu: "Последний день представления отчётности и уплаты НДФЛ и социального налога за ноябрь 2025 года.",
    descEn: "Last day to file and pay personal income tax and social tax for November 2025.",
    descUz: "2025 yil noyabr uchun JDST va ijtimoiy soliq bo'yicha hisobot topshirish va to'lashning oxirgi kuni.",
    descUzc: "2025 йил ноябрь учун ЖДСТ ва ижтимоий солиқ бўйича ҳисобот топшириш ва тўлашнинг охирги куни.",
    articleRef: "НК, ст. 389, 390",
  },
  {
    year: 2025, month: 12, date: new Date("2025-12-15"),
    taxType: TaxType.TURNOVER, eventType: EventType.BOTH,
    titleRu: "Отчётность и уплата налога с оборота за ноябрь 2025",
    titleEn: "Turnover tax return and payment for November 2025",
    titleUz: "2025 yil noyabr uchun aylanma solig'i hisoboti va to'lovi",
    titleUzc: "2025 йил ноябрь учун айланма солиғи ҳисоботи ва тўлови",
    descRu: "Последний день представления отчётности и уплаты налога с оборота за ноябрь 2025 года.",
    descEn: "Last day to file turnover tax return and pay turnover tax for November 2025.",
    descUz: "2025 yil noyabr uchun aylanma solig'i bo'yicha hisobot topshirish va to'lashning oxirgi kuni.",
    descUzc: "2025 йил ноябрь учун айланма солиғи бўйича ҳисобот топшириш ва тўлашнинг охирги куни.",
    articleRef: "НК, ст. 464",
    taxRegimes: [TaxRegime.TURNOVER],
  },
  {
    year: 2025, month: 12, date: new Date("2025-12-11"),
    taxType: TaxType.PROPERTY, eventType: EventType.PAYMENT,
    titleRu: "Авансовый платёж по налогу на имущество за декабрь 2025",
    titleEn: "Property tax advance payment for December 2025",
    titleUz: "2025 yil dekabr uchun mulk solig'i avans to'lovi",
    titleUzc: "2025 йил декабрь учун мулк солиғи аванс тўлови",
    descRu: "Последний день уплаты авансовых платежей по налогу на имущество за декабрь 2025 года (для плательщиков НДС) — в размере 1/12 части годовой суммы налога.",
    descEn: "Last day for property tax advance payment for December 2025 (VAT payers) — 1/12 of annual tax amount.",
    descUz: "2025 yil dekabr uchun mulk solig'i avans to'lovini amalga oshirishning oxirgi kuni (QQS to'lovchilari uchun) — yillik soliq summasining 1/12 qismi.",
    descUzc: "2025 йил декабрь учун мулк солиғи аванс тўловини амалга оширишнинг охирги куни (ҚҚС тўловчилари учун) — йиллик солиқ суммасининг 1/12 қисми.",
    articleRef: "НК, ст. 417, ч. 6",
    taxRegimes: [TaxRegime.VAT],
  },
  // 2026 events - Jan/Feb (Mar+ are in separate seed files)
  {
    year: 2026, month: 1, date: new Date("2026-01-20"),
    taxType: TaxType.VAT, eventType: EventType.BOTH,
    titleRu: "Отчётность и уплата НДС за декабрь 2025",
    titleEn: "VAT return and payment for December 2025",
    titleUz: "2025 yil dekabr uchun QQS hisoboti va to'lovi",
    titleUzc: "2025 йил декабрь учун ҚҚС ҳисоботи ва тўлови",
    descRu: "Последний день представления отчётности и уплаты НДС за декабрь 2025 года.",
    descEn: "Last day to file VAT return and pay VAT for December 2025.",
    descUz: "2025 yil dekabr uchun QQS bo'yicha hisobot topshirish va soliq to'lashning oxirgi kuni.",
    descUzc: "2025 йил декабрь учун ҚҚС бўйича ҳисобот топшириш ва солиқ тўлашнинг охирги куни.",
    articleRef: "НК, ст. 273, 274",
    taxRegimes: [TaxRegime.VAT],
  },
  {
    year: 2026, month: 1, date: new Date("2026-01-15"),
    taxType: TaxType.SOCIAL, eventType: EventType.BOTH,
    titleRu: "Отчётность и уплата НДФЛ и социального налога за декабрь 2025",
    titleEn: "Personal income tax and social tax for December 2025",
    titleUz: "2025 yil dekabr uchun JDST va ijtimoiy soliq",
    titleUzc: "2025 йил декабрь учун ЖДСТ ва ижтимоий солиқ",
    descRu: "Последний день представления отчётности и уплаты НДФЛ и социального налога за декабрь 2025 года.",
    descEn: "Last day to file and pay personal income tax and social tax for December 2025.",
    descUz: "2025 yil dekabr uchun JDST va ijtimoiy soliq bo'yicha hisobot topshirish va to'lashning oxirgi kuni.",
    descUzc: "2025 йил декабрь учун ЖДСТ ва ижтимоий солиқ бўйича ҳисобот топшириш ва тўлашнинг охирги куни.",
    articleRef: "НК, ст. 389, 390",
  },
  {
    year: 2026, month: 1, date: new Date("2026-01-15"),
    taxType: TaxType.TURNOVER, eventType: EventType.BOTH,
    titleRu: "Отчётность и уплата налога с оборота за декабрь 2025",
    titleEn: "Turnover tax return and payment for December 2025",
    titleUz: "2025 yil dekabr uchun aylanma solig'i hisoboti va to'lovi",
    titleUzc: "2025 йил декабрь учун айланма солиғи ҳисоботи ва тўлови",
    descRu: "Последний день представления отчётности и уплаты налога с оборота за декабрь 2025 года.",
    descEn: "Last day to file turnover tax return and pay turnover tax for December 2025.",
    descUz: "2025 yil dekabr uchun aylanma solig'i bo'yicha hisobot topshirish va to'lashning oxirgi kuni.",
    descUzc: "2025 йил декабрь учун айланма солиғи бўйича ҳисобот топшириш ва тўлашнинг охирги куни.",
    articleRef: "НК, ст. 464",
    taxRegimes: [TaxRegime.TURNOVER],
  },
  {
    year: 2026, month: 2, date: new Date("2026-02-20"),
    taxType: TaxType.VAT, eventType: EventType.BOTH,
    titleRu: "Отчётность и уплата НДС за январь 2026",
    titleEn: "VAT return and payment for January 2026",
    titleUz: "2026 yil yanvar uchun QQS hisoboti va to'lovi",
    titleUzc: "2026 йил январь учун ҚҚС ҳисоботи ва тўлови",
    descRu: "Последний день представления отчётности и уплаты НДС за январь 2026 года.",
    descEn: "Last day to file VAT return and pay VAT for January 2026.",
    descUz: "2026 yil yanvar uchun QQS bo'yicha hisobot topshirish va soliq to'lashning oxirgi kuni.",
    descUzc: "2026 йил январь учун ҚҚС бўйича ҳисобот топшириш ва солиқ тўлашнинг охирги куни.",
    articleRef: "НК, ст. 273, 274",
    taxRegimes: [TaxRegime.VAT],
  },
  {
    year: 2026, month: 2, date: new Date("2026-02-16"),
    taxType: TaxType.SOCIAL, eventType: EventType.BOTH,
    titleRu: "Отчётность и уплата НДФЛ и социального налога за январь 2026",
    titleEn: "Personal income tax and social tax for January 2026",
    titleUz: "2026 yil yanvar uchun JDST va ijtimoiy soliq",
    titleUzc: "2026 йил январь учун ЖДСТ ва ижтимоий солиқ",
    descRu: "Последний день представления отчётности и уплаты НДФЛ и социального налога за январь 2026 года.",
    descEn: "Last day to file and pay personal income tax and social tax for January 2026.",
    descUz: "2026 yil yanvar uchun JDST va ijtimoiy soliq bo'yicha hisobot topshirish va to'lashning oxirgi kuni.",
    descUzc: "2026 йил январь учун ЖДСТ ва ижтимоий солиқ бўйича ҳисобот топшириш ва тўлашнинг охирги куни.",
    articleRef: "НК, ст. 389, 390",
  },
  {
    year: 2026, month: 2, date: new Date("2026-02-16"),
    taxType: TaxType.TURNOVER, eventType: EventType.BOTH,
    titleRu: "Отчётность и уплата налога с оборота за январь 2026",
    titleEn: "Turnover tax return and payment for January 2026",
    titleUz: "2026 yil yanvar uchun aylanma solig'i hisoboti va to'lovi",
    titleUzc: "2026 йил январь учун айланма солиғи ҳисоботи ва тўлови",
    descRu: "Последний день представления отчётности и уплаты налога с оборота за январь 2026 года.",
    descEn: "Last day to file turnover tax return and pay turnover tax for January 2026.",
    descUz: "2026 yil yanvar uchun aylanma solig'i bo'yicha hisobot topshirish va to'lashning oxirgi kuni.",
    descUzc: "2026 йил январь учун айланма солиғи бўйича ҳисобот топшириш ва тўлашнинг охирги куни.",
    articleRef: "НК, ст. 464",
    taxRegimes: [TaxRegime.TURNOVER],
  },
];

async function main() {
  console.log("Seeding database...");

  // Create admin user
  const adminPassword = await bcrypt.hash("admin123!", 10);
  const admin = await prisma.user.upsert({
    where: { email: "admin@trek.uz" },
    update: {},
    create: {
      email: "admin@trek.uz",
      password: adminPassword,
      name: "Admin",
      role: "ADMIN",
      language: "ru",
    },
  });
  console.log("Admin user created:", admin.email);

  // Create demo user
  const demoPassword = await bcrypt.hash("demo123!", 10);
  const demo = await prisma.user.upsert({
    where: { email: "demo@trek.uz" },
    update: {},
    create: {
      email: "demo@trek.uz",
      password: demoPassword,
      name: "Демо пользователь",
      role: "USER",
      orgType: "LLC",
      taxRegime: "VAT",
      language: "ru",
    },
  });
  console.log("Demo user created:", demo.email);

  // Seed tax events
  let created = 0;
  for (const evt of events2025) {
    await prisma.taxEvent.create({
      data: {
        year: evt.year,
        month: evt.month,
        date: evt.date,
        taxType: evt.taxType,
        eventType: evt.eventType,
        titleRu: evt.titleRu,
        titleEn: evt.titleEn,
        titleUz: evt.titleUz,
        titleUzc: evt.titleUzc,
        descRu: evt.descRu,
        descEn: evt.descEn,
        descUz: evt.descUz,
        descUzc: evt.descUzc,
        articleRef: (evt as Record<string, unknown>).articleRef as string ?? null,
        orgTypes: (evt as Record<string, unknown>).orgTypes as string[] ?? [],
        taxRegimes: (evt as Record<string, unknown>).taxRegimes as string[] ?? [],
        requiresEmployees: (evt as Record<string, unknown>).requiresEmployees as boolean ?? null,
        requiresAssets: (evt as Record<string, unknown>).requiresAssets as string[] ?? [],
        requiresSpecial: (evt as Record<string, unknown>).requiresSpecial as string[] ?? [],
        requiresPension: (evt as Record<string, unknown>).requiresPension as string[] ?? [],
        forPeriod: (evt as Record<string, unknown>).forPeriod as string ?? null,
        isPublished: true,
        isDraft: false,
      },
    });
    created++;
  }
  console.log(`Created ${created} tax events`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
